### ISSUE TITLE
MAT 23:25-26

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/udb-en#100]
25 ".. You make yourselves appear like good people to others. You are like cups and plates that women have washed on the outside, but these things are dirty on their inside with food and drink that you have taken from others. 26 You blind Pharisees! First you must stop stealing from others. Then you will be able to do what is righteous. Then you will be like a cup that is clean both outside and in."

Discussion Panel post from Lizz Carlton:

Lizz Carlton, 2016-08-08 16:49 

TEXT: Suggested revision of UDB: 

"...**You try to make people think you are righteous, but in fact you sin against them/people by your greedy stealing. You are like cups and plates that are clean on the outside but are still dirty on the inside**. 26You blind Pharisees! First you must stop **doing evil/sinful things like stealing from others**. Then you will be able to do what is righteous **and** will be like a **dish** that is clean both outside and **inside**." 

Reasons:
 -- alternate: "You pretend to be doing good things" or "You make it seem like you are obeying God" -- having "women" makes it seem like this is part of the main point and distracts from the main point
 -- it isn't just about stealing food and drink -- more generally about stealing from others and in other ways taking advantage of them (extorting) for money. Better to keep it general.
 -- "evil things like stealing from others" -- they did other evil things, not just stealing
 --alternate: "You are like cups and plates that someone washed on the outside but left dirty on the inside."
 -- "dish" is a more general term that includes both a cup and a plate.

**Comment by hmw3** [comment]
Good suggestions. Now reads:
\v 25 "You hypocrites, you teachers of the law and you Pharisees, how terribly God will punish you! You make yourselves appear like good people to others. You try to make people think you are righteous, but in fact you sin against them by your greedy stealing. You are like dishes that are clean on the outside but are still dirty on the inside.
\v 26 You blind Pharisees! First you must stop doing evil things like stealing from others. Then you will be able to do what is righteous and will be like a dish that is clean both outside and inside."
