### ISSUE TITLE
Exo 16:28 UDB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#105]
EXO 16:28 UDB: Then Yahweh told Moses to say this to the people: "How long will you people refuse to do all the things that I tell you? Listen! Yahweh has given you ..."

This gives the impression that the word "I" refers to Moses and that he was the one that people were disobeying. (The ULB has "my commandments and my laws" and the word "my" refers to God.)

Suggested change to UDB:
Then Yahweh told Moses to say this to the people: "How long will you people refuse to do all the things that **Yahweh tells** you? Listen! Yahweh has given you ..."

**Comment by hmw3** [comment]
The ULB was a victim of inadvertent UDBism. I think I've straightened things out.
