### ISSUE TITLE
Exo 16 5 UDB 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#106]
Exo 16:5 UDB to Mount Sinai. 
I don't know why the TFT and UDB have this in 16:5.
16:6 refers to Mount Horeb. 
The two names in the same quote give the impression that these are two different mountains.

**Comment by TomWarren** [comment]
This is Exo 17:5-6 
UDB EXO 17:5-6 now read:
\v 5 Yahweh said to Moses, "Lead the people and walk in front of them. Take some of the elders of the Israelite people with you. Carry in your hand the staff you used to strike the Nile River.
\v 6 Listen to me! I will stand in front of you on top of a large rock at the foot of Mount Horeb. Strike the rock with your stick. When you do that, water for the people to drink will flow out of the rock." Moses did what God had said, and the elders were there with him when the water flowed out of the rock.

**Comment by SusanQuigley** [comment]
Tom, thank you for finding the right verses and for fixing it. (I was concerned that translators would think that Mount Sinai in 17:5 UDB and Horeb in 17:6 ULB were two different places.)

However, I just realized that there must have been a decision to use "Sinai" all the time in the UDB. "Horeb" occurs in the UDB only here and in Exo 3:1 and 1Ki 19:8.

So could you change Horeb back to Sinai in the UDB? With the names only occurring in v6, I think translators will be able to see that they refer to the same place

**Comment by TomWarren** [comment]
Sinai is replacing Horeb.
The UDB of EXO 17:6 now reads: 
\v 6 Listen to me! I will stand in front of you on top of a large rock at the foot of Mount Sinai. Strike the rock with your stick. When you do that, water for the people to drink will flow out of the rock." Moses did what God had said, and the elders were there with him when the water flowed out of the rock.

**Comment by SusanQuigley** [comment]
Thank you.
