### ISSUE TITLE
Exo 17:16 UDB vs ULB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#107]
Exo 17:16 UDB  Hold high Yahweh's flag 
Exo 17:16 ULB Yahweh has sworn

These are quite different.

**Comment by TomWarren** [comment]
The ULB of EXO 17:16 now reads: 
\v 16 He said, "For a hand was lifted up to the throne of Yahweh—that Yahweh will wage war with Amalek from generation to generation."

The UDB of EXO 17:16 now reads: 
\v 16 He said, "A promise was made in front of the throne of Yahweh: Yahweh will fight against the people of Amalek forever!"

The note about "a hand was lifted up" (a metonymy) was a way to make a promise or pledge.

**Comment by hmw3** [comment]
"A promise was made"


Can you unpack the passive? Who made it?

________________________________

**Comment by TomWarren** [comment]
It isn't clear who made the promise, only that a promise was made. Could 
be Yahweh. Could be the people.

Ambiguity in the Biblical text! I am shocked.


Tom

**Comment by SusanQuigley** [comment]
ULB: For a hand was lifted up to the throne of Yahweh—that Yahweh will wage war with Amalek from generation to generation.
UDB: A promise was made in front of the throne of Yahweh: Yahweh will fight against the people of Amalek forever!
**hand was lifted up** - a promise was made. The raised hand was used to make a promise or pledge (See: Metonymy)

If the promise is that Yahweh will wage war with Amalek, then it would seem that Yahweh must be the one who made the promise. Who else can promise what Yahweh will do?
But it seems odd that Yahweh would lift up his hand to his own throne. We'd expect him to be on the throne.

Translations that have "sworn" have it as the Lord who swore. So I'll put that in the note.
