### ISSUE TITLE
EXO 19:12 ULB bounds

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#108]
Exo 19:12  Could "set bounds" be changed to "set boundaries"?
I think "boundaries" is a more common word, and it will be the same as Exo 19:23.

**Comment by TomWarren** [comment]
Yes, the ULB of EXO 19:12 now reads: 
\v 12 You must set boundaries all around the mountain for the people. Say to them, 'Be careful that you do not go up the mountain or touch its border. Whoever touches the mountain will surely be put to death.'

The tN now has "boundaries" to conform to this change.

**Comment by SusanQuigley** [comment]
Thank you, Tom.
