### ISSUE TITLE
Exo 32:2 ULB Extra comma

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#109]
Exo 32:2  ULB and the ears of your sons, and daughters, 
The comma after "sons" is not needed.

**Comment by TomWarren** [comment]
The ULB of EXO 32:2 now reads: 
\v 2 So Aaron said to them, "Take off the golden rings that are on your wives' ears, and the ears of your sons and daughters, and bring them to me."

Thanks!
