### ISSUE TITLE
Luk 7:29 UDB

### ISSUE THREAD

**Issue by lrsallee** [Door43/udb-en#11]
The word "since" in the current version make the statement of the people the result of John's baptism. UBS handbook sees this as possible, but not preferred. Verse 30 is from the same Gk construction, but does not make that cause/effect relationship. 

Could we change v. 29 to read more like v. 30, with the emphasis being on inserting the participle "having been baptized" after the subject? I believe this would better read:

"When all the people who had been baptized by John, including tax collectors, heard what Jesus said, they agreed that God was just."

This would be more parallel to v. 30, and avoid taking sides on the meaning of the participle.

**Comment by TomWarren** [comment]
I switched it around a bit, but here it is:

\v 29 When all the people who had been baptized by John heard what Jesus said—including the tax collectors—they agreed that God was just.
\v 30 But the Pharisees and the experts in the Jewish laws had not been baptized by John and they rejected God's will for them.
