### ISSUE TITLE
Exo 32:23 ULB Single quote mark needs to be moved

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#110]
Exo 32:23 ULB So I said to them, 'Whoever has any gold, let him take it off.*  They gave me the gold and I threw it into the fire, and out came this calf.'"

The single quote mark closing off what Aaron had said to the people should be where I put the asterisk, and it needs to be removed from the end. (The end should have only the double quote mark closing off what Aaron said to Moses.)

**Comment by TomWarren** [comment]
The ULB now reads: 
\v 24 So I said to them, 'Whoever has any gold, let him take it off.' They gave me the gold and I threw it into the fire, and out came this calf."

Thanks.
