### ISSUE TITLE
Exo 32:29 ULB & UDB son and brother

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#111]
Exo 32:29
ULB for each of you has acted against his brother,
UDB by killing even your brothers.

Both of these are missing the idea of sons.

**Comment by TomWarren** [comment]
The ULB at EXO 32:29 now reads, 
\v 29 Moses said to the Levites, "You have been placed into Yahweh's service today, **for each of you has taken action against his son and his brother,** so Yahweh might give you a blessing today."

The UDB at EXO 32:29 now reads, 
\v 29 Moses said to the men in the tribe of Levi, "Today you have become special servants of Yahweh **by killing even your own sons and your brothers.** As a result Yahweh has blessed you."

Thanks for catching that omission.
