### ISSUE TITLE
Remove \q Markers in UDB

### ISSUE THREAD

**Issue by jag3773** [Door43/udb-en#113]
_From @jag3773 on January 21, 2016 23:50_

The \q markers need to be removed from the UDB.  Note well, we are talking about the UDB, the **dynamic** version.

Please remove them from the book of Joel first and make a pull request against https://github.com/unfoldingWord/udb-en.  Have Jim review.

If he is happy with the changes then we should run the script on the whole OT.  This should result in another PR that can be reviewed and merged when we get Jim's approval.

_Copied from original issue: unfoldingWord-dev/Door43#449_

**Comment by jag3773** [comment]
_From @destatez on February 10, 2016 20:16_

Jesse

I'm a little confused. I thought, from earlier discussions, that the repository was populated from etherpad, which is the "root" source of the data. The implications from your comments is that the repository is the "root" and if the text mods are pushed back up, they will then get populated into etherpad. Can you clarify this for me?

**Comment by jag3773** [comment]
_From @destatez on February 11, 2016 14:49_

A further concern is that I just compared the pulled repository file \ulb\v2\1sa\031.usfm.txt with the latest version in etherpad and the Door43 htm associated page and they do not align, particularly for verse 12, which was update 2/10/2016. The repository seems to have a very "antique" version of that verse. (I know that this ULB verse has nothing to do with this issue, but it evidences my concern)

**Comment by jag3773** [comment]
_From @ChrisJarka on May 27, 2016 12:20_

Should this issue be closed and moved to https://github.com/Door43/udb-en/issues?

**Comment by pohlig** [comment]
Actually, who is going to remove the \q markers in Joel UDB? (Remember to remove **all** q markers, that is, \q1 and \q2, as well.)
But I and Tom Warren really really need to see Joel UDB after these markers are removed, so we can ensure that the text has come out alright.
IN FACT, PLEASE LET US KNOW BEFORE YOU TRY TO REMOVE THE Q MARKERS.
