### ISSUE TITLE
PSA 10:12 judge them or help us?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#114]
UDB: God, **help us** with your power!
ULB: lift up your hand **in judgment**, God.

UDB and ULB interpret "lift up your hand" differently.

**Comment by TomWarren** [comment]
I extensively reworked UDB PSA 10. The text had changed the singular to the plural. Now the ULB and the UDB have the same person (helping the MTT).

The Heb "lift up your hand" should be translated, "strike them." 
The UDB PSA 10:12 now reads: 
\v 12 Yahweh, arise! God, strike him down!
\q2 Do not forget those who are suffering!

The ULB PSA 10:12 now reads: 
\v 12 Arise, Yahweh! Strike him down, God!
\q Do not forget the oppressed.

**Comment by TomWarren** [comment]
Jim and I agree that the ULB should read: 
\v 12 Arise, Yahweh! Lift up your hand, God!
\q Do not forget the oppressed.

And the UDB can be more explanatory (as is its purpose). I will check the notes.

**Comment by SusanQuigley** [comment]
Thank you, Tom.
