### ISSUE TITLE
PSA 10:16 ULB/UDB Yahweh is king/King

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#117]
10:16 UDB Yahweh is king 

The ULB sometimes has King capitalized when it refers to God, and sometime lower case (Psa 22:3 and 29:10 both with "you sit as king," 74:12, 89:18)
The UDB sometimes has it capitalized when it refers to God (Ps 5:2, 44:4) and sometimes lower case (Ps 29:10, 47:2, 69:34, 74:12, 84:3, 92:18)

I only looked up through Psalm 89.

**Comment by TomWarren** [comment]
The agreed-upon rule was that if it was his name, as in King Yawheh, it would be caps. Like King David. But if it were office or description it would not be, like David is the king of Israel. 
I will search for upper case King in the OT and see if they can be corrected.
