### ISSUE TITLE
PSA 10:15 UDB Make him pay

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#119]
10:15 UDB
God, you destroy the power of the wicked person
and the strength of the evil person!
**Make the wicked person pay for the evil things he has done!**
**Make him pay for those evil things he did,**
those thingas for which he never thought God would punish him.

It looks like one of the bolded lines was a correction and the old one should be deleted

**Comment by TomWarren** [comment]
There was an apparent correction that was not erased. 
UDB PSA 10:15 now reads: 
\v 15 God, you destroy the power of the wicked person 
\q2 and the strength of the evil person!
\q2 Make him pay for those evil things he did, 
\q2 those things for which he never thought God would punish him. 
\b
