### ISSUE TITLE
PSA 52:7 UDB wealth or wickedness

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#120]
52:7 UDB he trusted in the money that he got by wickedly taking it from others!" 
This looks like a dynamic translation of "in his wealth" from the Syriac and Targum. 

The Masoretic text has "in his wickedness," and the ULB has the same. 

It would probably be good to change the UDB to reflect "in his wickedness," maybe something like one of these:
"he trusted in his wicked deeds"
"he trusted that his wicked deeds would protect him"

**Comment by TomWarren** [comment]
I dealt with some of this in the other post on  PSA 52.

**Comment by SusanQuigley** [comment]
Thanks, Tom. This looks good. 
52:7b in both versions is about him trusting in his wealth,
and 52:7c in both versions is about him being strong (or strengthened) when he destroyed others.
