### ISSUE TITLE
PSA 53:4 UDB   "while they eat bread" vs "like eating bread"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#122]
PSA 53:4
ULB: Do they not know anything, those who commit iniquity,
those who eat up my people **as they eat bread**
but who do not call on God?

 UDB Will all these evil people never learn what God will do to them?
They act violently toward Yahweh's people **while eating the food that he provides,**
and they never pray to Yahweh.

Many versions simply have "as they eat bread." In English it is ambiguous. It could mean "in the same way that they eat bread" or "while they eat bread."
Most versions that clarify the meaning treat it as a simile - "as if they were eating bread", "like food"

Could the UDB treat it as a simile rather than a simultaneous activity? Maybe something like this:
They act violently toward Yahweh's people, destroying them as easily as people eat bread.

**Comment by TomWarren** [comment]
I dealt with this in another PSA 53 Issue. 
Here it is: 
UDB PSA 53:4 now reads: 
\v 4 Will all these evil people never learn what God will do to them?
\q1 They hurt Yahweh's people with terrible violence, while they are enjoying the very food that God provided for them.
\q2 Still, they never pray to Yahweh.

ULB PSA 53:4 now reads: 
\v 4 Do those who commit iniquity, not know anything—
\q those who devour my people as if they were eating bread
\q and who do not call on God?
Tom

**Comment by SusanQuigley** [comment]
Thank you. It works now.
