### ISSUE TITLE
PSA 57:10 UDB unfinished sentence

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#125]
PSA 57:10 UDB
I will sing to praise you among many people groups,
10 because your faithful love for us is as great as the distance from the earth to the sky,
**and because your faithfulness**. 

The last line is missing something.

**Comment by TomWarren** [comment]
UDB PSA 57:19 now reads: 
\v 10 because your faithful love for us is as great as the distance from the earth to the sky,
\q2 and because your faithfulness goes as far as the clouds.

Thanks.

**Comment by SusanQuigley** [comment]
Ok, thanks Tom. I asked Andrew too add "unfailing love" to the title of the tW page for "covenant faithfulness," and this is how I explained the ellipsis in "and your faithfulness to the clouds"

**and your faithfulness to the clouds** - The words "great is your" and "reaching" are understood from the previous phrase. AT: "and great is your faithfulness, reaching to the clouds" or "and your faithfulness is as great as the distance from the earth to the clouds" (See: Ellipsis and Metaphor)

**Comment by TomWarren** [comment]
Good. That is really helpful. And wonderful for the heart, too. 
Tom
