### ISSUE TITLE
PS 105:32 hail and rain

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#126]
UDB Instead of sending rain, Yahweh sent terrible hail,

ULB He sent hail and rain,

These contradict. It was decided in earlier discussion to go with both hail and rain.

**Comment by TomWarren** [comment]
Rain and hail seem connected (not separate events).
The ULB PSA 105:32 (following the Heb) reads: 
\v 32 He turned their rain into hail, 
\q with fire flaming on their land.

The UDB PSA 105:32 now reads: 
\v 32 Yahweh sent rain, rain that became hail that fell upon them,
\q2 and he sent wild fires that burned throughout their land.

Hope that helps. 
TW
