### ISSUE TITLE
NUM 11:6  ULB vs UDB weak or desire to eat?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#129]
ULB **Now we are weak.** We see nothing to eat but manna."
UDB But **now we do not have any desire to eat,** because all we have to eat is this manna!"

There are different meanings in the first clause.

**Comment by TomWarren** [comment]
UDB NUM 11:6 now reads: 
\v 6 But now we have lost our appetite, because all the food there is for us to look at is this manna!"

ULB NUM 11:6 now reads: 
\v 6 Now our appetite is gone, because all we can see is this manna."
 
Thanks,
TW

**Comment by SusanQuigley** [comment]
Thank you.
