### ISSUE TITLE
NUM 13:11  UDB lacks "Joseph"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#131]
ULB From Joseph's descendants, namely, from the tribe of Manasseh, Gaddi son of Susi.
UDB Gaddi son of Susi, from the tribe of Manasseh;

Maybe UDB could have something like this:
Gaddi son of Susi, from the tribe of Joseph's descendent Manasseh;

**Comment by TomWarren** [comment]
UDB NUM 13:9-12 now reads: 
\v 9 Palti son of Raphu, from the tribe of Benjamin;
\li1
\v 10 Gaddiel son of Sodi, from the tribe of Zebulun;
\li1
**\v 11 Gaddi son of Susi, from the tribe of Joseph's descendent Manasseh;**

\li1
\v 12 Ammiel the son of Gemalli, from the tribe of Dan;

**Comment by SusanQuigley** [comment]
Thank you. :)
