### ISSUE TITLE
NUM 15:39  UDB unacceptable or unfaithful?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#133]
UDB:  as a result causing yourselves to become unacceptable to me.
ULB: after which you used to act like spiritual prostitutes.

I see that being unfaithful like prostitutes is a shameful thing and would make people unacceptable to God, and v. 40 talks about them being holy to God (which could be seen as in contrast to "unacceptable"),  but I wonder if this phrase in the UDB should be more about them being unfaithful or shamefully unfaithful.

Also, for the ULB, I wonder about the past tense.

**Comment by pohlig** [comment]
I've changed both versions to:

Num. 15:39  and prostitute yourselves to them ulb

instead of being unfaithful to me and doing the shameful things you desire
udb

Thanks. Jim

**Comment by SusanQuigley** [comment]
Thanks.
