### ISSUE TITLE
NUM 16:9 UDB  the God of us Israelis

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#134]
UDB the God of us Israelis

"Israelis" should be "Israelites"

Also Deut 17:20  his fellow Israelis

**Comment by TomWarren** [comment]
ULB NUM 16:9 now reads; 
\v 20 If he does that, he will not think that he is more important than his fellow Israelites, and he will completely obey Yahweh's commands. As a result, he and his descendants will rule as kings in Israel for many years."

**Comment by SusanQuigley** [comment]
Thank you. The change shows up in Deut 17:20, but it doesn't show up yet in Num 16:9.

**Comment by TomWarren** [comment]
Should be there now.

**Comment by SusanQuigley** [comment]
Thanks. I see it now-- "the God of Israel"
Looks good.
