### ISSUE TITLE
NUM 18:16 UDB weight or value of the pieces?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#135]
UDB: The price that they must pay for each one is five pieces of silver * . They must weigh the silver on the scales that are in the sacred tent.
ULB:  Then the people may buy them back, for the price of five shekels, by the standard weight of the sanctuary shekel, which equals twenty gears.

The UDB gives no indication of the weight or value of the silver. I would like the MTTs to have an example without having to write a long note. Could the following be added to the  UDB where I put the asterisk.
* each piece weighing eleven grams

**Comment by TomWarren** [comment]
Yes, that has been the model to explain weights in common terms. The ULB would render the term in the way the original texts have them. "talent, shekel, hand, etc". It might be rendered, "the price that they must pay for each one is eleven grams of silver."  Your call. 

TW

**Comment by SusanQuigley** [comment]
I wrote a note, so the UDB can probably stand as is.
But  if it's important to include the information that there were various weights for shekels and God wanted them to be sure to use the right weight  shekel, here's one way of making it clear in the UDB.

"The price that they must pay for each one is five pieces of silver. Each piece of silver must weigh eleven grams, the weight that is used in the sacred tent."

Or since we're not exactly sure of the metric equivalents of the sanctuary shekel and gerah, the UDB could say "ten grams."

**Comment by TomWarren** [comment]
There is a second on weights and measures in the Translation Academy, as you know. There are many issues about shifting weights and measures, and some of them seem unresolvable. The shekel is not a coin (as you know) but a hunk of metal at a rate that is standardized. Sure you know that. Just blabbing along.

**Comment by pohlig** [comment]
Yes, and shaqal in Hebrew, of course, means to weigh something, or to weigh out something, like gold dust, etc. It was an action common when paying in precious metals for things, before coins were minted.

**Comment by SusanQuigley** [comment]
So Is it likely that people used small pieces of silver that each weighed one shekel, or that they carried  pieces of silver of various weights and had to add them to a scale until they reached the required weight?

**Comment by pohlig** [comment]
The second is what was likely. Coinage was not minted in Israel until sometime in the fourth century, under the Persian Empire BC. Tyre had coinage from c. 300 BC.

**Comment by SusanQuigley** [comment]
Ok. Thanks. That helped me come up with another AT.
