### ISSUE TITLE
NUM 18:24  one tenth of what?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#136]
UDB: I will give you one tenth of all the crops and animals that the Israelites present as offerings to me
The UDB sounds like Yahweh will give a tenth of the offerings that the Israelites present. 
It should say that Yahweh will give the offerings that the Israelites present, which are a tenth of the crops and animals. 
(Compare ULB and vv. 26-27 of both, where the Levites are told to give a tenth of what they receive to Yahweh.)

**Comment by TomWarren** [comment]
The UDB now reads with changes:  UDB NUM 18:24
\v 23 Only the descendants of Levi are permitted to work at the sacred tent, and they will be punished if anything bad happens to it. That is a law that will never be changed. You descendants of Levi will not receive any land to own among all the other Israelite people.
\v 24 But I give to the descendents of Levi one tenth of all the crops and animals that the Israelites present as offerings to Yahweh. This is how I provide for them, and this is why I said that they will not be given any land to own.
The parallel in the ULB reads (without change):
\v 23 The Levites must do the work connected to the tent of meeting. They will be responsible for any sin regarding it. This will be a permanent law throughout your people's generations. And among the people of Israel they must have no inheritance.
\v 24 For the tithes of the people of Israel, which they offer as a presented offering to me—it is these that I have given to the Levites as their inheritance. That is why I said to them, 'They must have no inheritance among the people of Israel.'"

There you go.

**Comment by SusanQuigley** [comment]
Now the UDB sounds like the Israelites will present some offerings to God, and God will give the Levites one tenth of those offerings.
In the ULB it sounds like the Israelites will take one tenth of their produce and give it to God as an offering, and that God would give that whole offering to the Levites.

**Comment by TomWarren** [comment]
The UDB now reads: 
\v 24 One tenth of all the crops and animals that the Israelites present as offerings to Yahweh, I give to the descendents of Levi so they can provide for themselves. This is why I said that I will not be give the descendants of Levi any land to own.

**Comment by SusanQuigley** [comment]
Could it be something like this?
I will give you **the** tenth of all the crops and animals that the Israelites present as offerings to me ... 
OR
**The** tenth of all the crops and animals that the Israelites present as offerings to Yahweh, I give to the descendents of Levi ... 
OR
"The Israelites must present one tenth of all their crops and animals as offerings to me, and that is what I give to the descendants of Levi ...

**Comment by TomWarren** [comment]
I surrender: UDB NUM 18:24
\v 24 The Israelites must present one tenth of all their crops and animals as offerings to me, and that is what I give to the descendents of Levi so they can provide for themselves. This is why I said that I will not give the descendants of Levi any land to own.

Sorry, just didn't see the issue. Now I understand. The shift from Yahweh as the speaker and the other as Yahweh in the third person. So irritating to see these shifts between ULB and UDB. There is the purpose that some MTTs must put the prime subject as the speaker. 
TW

**Comment by SusanQuigley** [comment]
Thank you, Tom.
