### ISSUE TITLE
NUM 19:3 Who would slaughter it?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#137]
UDB: Give it to Eleazar, the priest. He must take it outside the camp and slaughter it and catch the blood in a basin. 
ULB: Give the heifer to Eleazar the priest. He must bring it outside the camp, and someone must kill it in front of him.
The UDB says that Eleazar would slaughter it. The ULB and other versions indicate that someone else was to slaughter it before Eleazar. 

Also UDB  v. 4 He must dip one of his fingers in the blood and sprinkle some of it seven times on the ground near the sacred tent. 
It would be good to change "He" to "Eleazar" to make it clear that Eleazar was the one to sprinkle the blood, not the person who burned the heifer in front of Eleazar.

**Comment by TomWarren** [comment]
There was some additional information that was not in the original text that was edited out. 
The UDB of NUM 19:3-4 now reads:
\v 3 Give it to Eleazar, the priest. He must take it outside the camp and someone will slaughter it.
\v 4 And Eleazar must dip one of his fingers in the blood and sprinkle some of it seven times on the ground near the sacred tent.
