### ISSUE TITLE
Numbers 20:7-8 ULB  "your staff" to "the staff"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#138]
ULB Yahweh spoke to **Moses** and said, "Take **your** staff 

Since it says that Yahweh spoke to Moses, and since the staff belonged to Aaron, could "your staff" be changed to "the staff"?

**Comment by TomWarren** [comment]
ULB of NUM 20:7 now reads: 
\v 8 "Take the staff and assemble the community, you, and Aaron your brother. Speak to the rock before their eyes, and command it to flow with water. You will produce water for them out of that rock, and you must give it to the community and their cattle to drink."
