### ISSUE TITLE
3Jn 1:5 UDB - stray code strings

### ISSUE THREAD

**Issue by lrsallee** [Door43/udb-en#14]
There is a string of equal signs at the end of this verse.

**Comment by lrsallee** [comment]
Actually, this and other stray code is throughout 3Jn.

**Comment by hharrissWA** [comment]
I suppose all this stray code needs to be deleted. I will do that, but just want to make sure there is no purpose in it before doing so.

**Comment by lrsallee** [comment]
Harry,

We found out this code indicates unsynced edits that need to be fixed. Tom and Dave are going to work on this. Better leave it alone for now.

Larry

**Comment by hharrissWA** [comment]
Will do, Larry.

Thanks!

Harry


C. Harry Harriss

Associate Editor, Unfolding Word Bible

Translation Consultant (in training)

Wycliffe Associates and Wycliffe India

harry_harriss@wycliffeassociates.org<mailto:harry_harriss@wycliffeassociates.org>

662-890-5637 home


________________________________

**Comment by TomWarren** [comment]
I think the edits are fixed now.

Tom

**Comment by hharrissWA** [comment]
Great!

Thanks,

H


C. Harry Harriss

Associate Editor, Unfolding Word Bible

Translation Consultant (in training)

Wycliffe Associates and Wycliffe India

harry_harriss@wycliffeassociates.org<mailto:harry_harriss@wycliffeassociates.org>

662-890-5637 home


________________________________
