### ISSUE TITLE
Lev 23:1-2 UDB Yahweh said ... "... we"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#140]
Lev 21:1-2 UDB   Yahweh said to Moses, 2"Tell the Israelites about the festivals for Yahweh, the days when you all must gather together in holy assemblies and **we have them** on set times each year, 

This sounds like God is participating in the festivals.
But God set the times for the festivals.

**Comment by TomWarren** [comment]
Just cut out a bit of the UDB. 
The UDB at LEV 23:2 now reads; 
\v 2 "Tell the Israelites about the festivals for Yahweh, the days when you all must gather together in holy assemblies on set times each year, as festivals in which you worship me.

**Comment by SusanQuigley** [comment]
That fixes it well. Thank you.
