### ISSUE TITLE
Lev 23:15 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#141]
ULB You must count from the day after that Sabbath, from the day that you brought the sheaf of the offering to be lifted up and presented, seven full weeks, seven Sabbaths, 16until the day after the seventh Sabbath. That is, you must count fifty days. Then you must offer an offering of new grain to Yahweh.
UDB: Seven weeks after the priest offers that flour to me, on the next day after he offers it, each family must bring to me an offering from the new crop of grain.

The UDB is confusing. It seems to equate "seven weeks after the priest offers that flour" to  "the next day after he offers it." It is not clear **when** each family must bring an offering. Could the UDB be changed to something like one of these? 

Seven weeks and one day after the priest offers that flour to me, each family must bring to me an offering from the new crop of grain.
OR
Seven weeks and one day after the priest offers the flour that you bring to me, each family must bring to me an offering from the new crop of grain.

**Comment by TomWarren** [comment]
The ULB needs to be straightened out first: 

ULB LEV 23:15-16 now reads: 
\v 15 Beginning from the day after the Sabbath—that was the day you brought the sheaf of the wave offering—count off seven full weeks.
\v 16 You must count fifty days, which would be the day after the seventh Sabbath. Then you must present an offering of new grain to Yahweh. 

UDB LEV 23:15-16
\v 15 Seven weeks and one day after the priest offers that flour to me, each family must bring to me an offering from the new crop of grain.
\v 16 Then count seven weeks and one day, that would be the day after the seventh Sabbath day, and on that day each family must bring to me an offering from the new crop of grain.

These counting days and Sabbaths are difficult. TW

**Comment by SusanQuigley** [comment]
ULB - What you wrote above is much clearer than what was in the ULB before. It's just not showing up yet in the USFM file or on the tN page. (I understand the first sentence in v 16 to be an explanation of what is meant in v. 15  "beginning from the day after ... count off seven full weeks".)

UDB -  I find what you wrote above confusing. The word "Then" at the beginning of v 16 makes it sound like there are two periods of seven weeks and one day.  I'm trying to think of a way of wording it so it is clear that there is only one period of time that they are to count.

**Comment by SusanQuigley** [comment]
Suggestion for UDB:
\v 15 Count seven weeks and one day after the priest offers that bundle of grain to me. 
\v 16 Then on the day after the seventh Sabbath, each family must bring to me an offering from the new crop of grain.

**Comment by TomWarren** [comment]
Try this: UDB LEV 23:15-16
\v 15 You are to count seven weeks and one day after the priest offers that bundle of grain to me, then on that day each family must bring to me an offering.
\v 16 That would be seven weeks plus one day. And so on the day after that seventh Sabbath day, each family must bring to me an offering from the new crop of grain.

There was a delay  (I think I was filling up my cache on my computer and it was taking time to organize all the changes I was making). It seems caught up now.

**Comment by TomWarren** [comment]
The UDB now has your suggestion: 
\v 15 Count seven weeks and one day after the priest offers that bundle of grain to me.
\v 16 Then on the day after the seventh Sabbath, each family must bring to me an offering from the new crop of grain.

I was trying to keep every concept in the verse. It was just too complicated in this case. Your suggestion was a good one. It is difficult for me to shorten the phrase, where it is repeating an idea, because I presume it was repeated for emphasis. But this is a good solution. 
The postings are working now.

**Comment by SusanQuigley** [comment]
Thanks, Tom. 
The ULB that shows up on the notes page is a little different from what you wrote in your first comment above. It is missing the word "count" in v 15. 

Beginning from the day after the Sabbath—that was the day you brought the sheaf of the wave offering—***** seven full weeks. 16You must count fifty days, which would be the day after the seventh Sabbath. Then you must present an offering of new grain to Yahweh.

**Comment by TomWarren** [comment]
The ULB is:
\v 15 Beginning from the day after the Sabbath—that was the day you brought the sheaf of the wave offering—count seven full weeks.
\v 16 You must count fifty days, which would be the day after the seventh Sabbath. Then you must present an offering of new grain to Yahweh.

**Comment by TomWarren** [comment]
I was messing around with this too much on line. Should have worked it out before posting it. Just trying to do too many at once. 
Thanks for your patience.

**Comment by SusanQuigley** [comment]
It's a lot of work and it's not easy. Thanks so much for doing it.
