### ISSUE TITLE
LEV 23:15 ULB vs UDB  Sheaf or flour?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#142]
ULB:  from the day that you brought **the sheaf** of the offering to be lifted up and presented, 
UDB: after the priest offers **that flour** 

I don't see any version that translate this is "flour." Could UDB be changed to something like this?

after the priest offers **that bundle of grain**

**Comment by TomWarren** [comment]
This was changed in the previous Issue.

**Comment by SusanQuigley** [comment]
Thank you.
