### ISSUE TITLE
Lev 25:11 -12 UDB translation of Jubilee

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#144]
ULB The fiftieth year will be a **jubilee** for you. You must not plant or conduct an organized harvest. Eat whatever grows by itself, and gather the grapes that grow on the unpruned vines. 12For it is a **jubilee**, which will be holy for you. You must eat the produce that grows by itself out of the fields.

UDB  This year, the fiftieth year, will be **a year in which you must rejoice and obey Yahweh's special instructions**. During that year do not plant anything, and do not harvest in your usual manner the crops or grapes that have grown by themselves. 12It will be **a year for you to rejoice in**. You will treat it as special, and eat only what has grown by itself.

I think the translation of "jubilee" in the UDB as" a time for rejoicing" reflects a modern English definition of jubilee rather than the traditional Jewish definition, which is  "a year of restoration" or "a year to return land and free slaves."  I think the point of saying that it is a year of jubilee in these instructions to allow the land to lie fallow is that the land belongs to the Lord, and in the year of restoration, they were to return the land to the Lord.

Could the UDB be changed to something like this?

UDB  This year, the fiftieth year, will be **a year in which you must return the land to me**. During that year do not plant anything, and do not harvest in your usual manner the crops or grapes that have grown by themselves. 12It will be **a year for you to return the land.** You will treat it as special, and eat only what has grown by itself.

**Comment by SusanQuigley** [comment]
The UDB also translates "Jubilee" or "year of Jubilee" as "year of celebration in the following verses.
Lev 25:15 (twice)
Lev 25:16 (twice)
Lev 25:27, 28, 30, 31, 33, 40, 50, 51, 52, 54
Lev 27: 21, 23, 24
Num 36:4

**Comment by TomWarren** [comment]
The issues of jubilee is that there was also freedom from servitude (when one Jew may indenture himself, like an apprentice), and on jubilee he would be a free person, reflecting the freedom from slavery in Egypt before the Exodus. One of the difficulties is that it seems that this celebration was not part of normal life in Israel. LEV 25;8-34 has the jubilee law; there is the anticipation of a future jubilee in EZK 46:17; there are illusions to the principle with Naboth and Ahab (855BCE, 1KI 21:3 with 22:1; The sabbatical years and the jubilee were not celebrated during the postexilic time, as well (Neh 10:31; cp 1 MAC 6:49, 53).
Will think about it some more.

**Comment by SusanQuigley** [comment]
These are translationNotes I've written:
**the jubilee** - "the year of restoration" or "the year to return land and free slaves"
**a jubilee for you** - "a year of restoration for you" or "a year for you to return land and free slaves"

Sometimes I did not include "free slaves" if the context was about the land, or "return land" when the context was about slaves.

**Comment by TomWarren** [comment]
I worked through the jubilee references in the UDB and made them more consistent, like "the year of celebration of Jubilee (we should be capitalizing Jubilee, it is the name of a feast, like Purim). That should help. I ran through Lev 25 and 27, Num 36 and the section in Ezk. They are consistent now.

**Comment by SusanQuigley** [comment]
Thank you  for doing that. That was a lot of work.
