### ISSUE TITLE
Lev 27:32 UDB Extra space

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#146]
Lev 27:32 UDB  There is an extra space before the period in the first sentence and before the period at the end of the verse.
Lev 27:33 UDB There is an extra space between "Yahweh" and the comma in the last sentence.

**Comment by TomWarren** [comment]
Thanks. Both spaces are removed.
TW

**Comment by SusanQuigley** [comment]
Thank you. Please also delete the space between "Yahweh" and the period at the end of the first sentence in v 27:32.

**Comment by TomWarren** [comment]
That is done. It just took its own sweet time. Thanks.

**Comment by TomWarren** [comment]
There appeared to be some glitches going on.
