### ISSUE TITLE
JDG 18:12 space

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#149]
On their way they set up their tents near the city of Kiriath Jearim in the area where the tribe of Judah live. That is why the area west of KiriathJearim was named Mahaneh Dan (or the "Camp of Dan"), and that is still its name.

Space needed between Kiriath and Jearim.

**Comment by hmw3** [comment]
Done.

**Comment by TomWarren** [comment]
There were two. 
\v 12 On their way they set up their tents near the city of Kiriath Jearim in the area where the tribe of Judah live. That is why the area west of Kiriath Jearim was named Mahaneh Dan (or the "Camp of Dan"), and that is still its name.
