### ISSUE TITLE
JDG 19:22

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#150]
While they were having a good time together, some wicked men from that city surrounded the house and started to bang on the door. They shouted to the old man, "Bring out to us the man who has come to your house. We want to have sex with him." 

I remember in the beginning of phase 2 we were getting rid of the word "sex" among others. The phrase "have sex with" should be changed to "sleep with."

**Comment by hmw3** [comment]
It's interesting that in this process we have ousted the Heb euphemism "know" for the specific "have sex with" and then ousted that for another euphemism. Maybe we should go back to "know" and explain it either as a standard note or a tW.

________________________________

**Comment by kim-putter** [comment]
Funny..the ULB does maintain "know" here. Hmm, I see that the next chunk has discussion stating that the word "rape" was removed, but it seems to be put back in. Oh well, I guess those higher up have made changed some of the decisions they made on the filter words. Anyways.

**Comment by TomWarren** [comment]
It is clearer for the translator to say "had sex with" than "slept with." There was an alarm raised that using "sex" and terms of human anatomy might trigger internet filters. That was found not to be the case. 
It would require additional explanation for the MTT, to tie "sleep with" to "sexual relations" and it wouldn't be necessary. 
Thanks for being careful about the text. If the text used a metaphor for sex, that metaphor would be preserved in the ULB and unpacked in the UDB. Here there is no metaphor.
Thanks
