### ISSUE TITLE
JOS 6:4 UDB is missing the ark

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#151]
The UDB doesn't say anything about the ark being in the procession around Jericho.

UDB: Tell seven priests to march around with them. They will each carry a trumpet *.

Could this be added where I put the asterisk?  "and march in front of the ark"

From v 13 it looks like it was first the armed soldiers, then the 7 priests with their trumpets, then the ark, and then the rear guard.

**Comment by TomWarren** [comment]
Here is the UDB of JOS 6:4
\v 4 Tell seven priests to march around with them. They will each carry a trumpet as they march before the sacred chest of Yahweh. On the seventh day, the army must march around the city seven times, and the priests must play the trumpets with a loud blast of sound while they march.

**Comment by SusanQuigley** [comment]
Thank you.
