### ISSUE TITLE
JOS 6:8 UDB  "started" or "began"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#152]
JOS 6:8  UDB: the seven priests, each carrying a trumpet, **started began** moving forward as Yahweh had directed. 

Please delete either "started" or "began."

**Comment by TomWarren** [comment]
Cleaned up the UDB. The UDB of JOS 6:8 now reads:
\v 8 Just as Joshua commanded his army, the seven priests, each one carrying a trumpet, marched as Yahweh had directed them. As they walked around the city, the priests gave a blast on their trumpets. The ones who carried Yahweh's sacred chest followed them.
