### ISSUE TITLE
MAT 1:12 UDB  "the ancestor" to "an ancestor"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#153]
MAT 1:12 Shealtiel was the ancestor of Zerubbabel. 

Since Zerubbabel had many ancestors, could "the ancestor" be changed to "an ancestor"?

**Comment by TomWarren** [comment]
The UDB has **an ancestor** for Joram and for Shealtiel, and Josiah has **grandfather**. It does seem more consistent to only divert from "father of" in one way "an ancestor" as the ULB has, but this is not crucial. It can stand like it is.
Thanks
