### ISSUE TITLE
ISA 13:12 UDB  I will stop ruthless people from acting cruelly

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#155]
UDB I will stop ruthless people from acting cruelly.
ULB will bring down the arrogance of the ruthless.

Could the UDB be changed to something more like the ULB? 
I will stop cruel people from being so arrogant
I will humiliate cruel people
I will humiliate proud, cruel people

**Comment by hmw3** [comment]
First alternative followed.

**Comment by SusanQuigley** [comment]
Thank you.
