### ISSUE TITLE
1SA 17:8 UDB Delete "I think"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#156]
UDB:  I am the great Philistine soldier,and **I think** you are merely Saul's slaves. 
ULB: Am not I a Philistine, and are you not servants of Saul? 

Could "I think" be deleted from the UDB?

**Comment by TomWarren** [comment]
Try this. With some editing: 
UDB 1SA 17:8 now reads:
\v 8 Goliath stood there and shouted to the Israelite army, "Why are you all lined up for battle? Can you see that I am a Philistine soldier who is ready to fight?  I can see that you are just the slaves of Saul. Choose one man who can fight for all of you and send him down here to me!

**Comment by hmw3** [comment]
It should be "You can see ...." instead of "Can you see ...?" because we should be unpacking RQs in the UDB.

________________________________

**Comment by TomWarren** [comment]
Good. I was thinking about the RQ here, but it could be requesting information, stick with the RQ.

The UDB of 1SA 17:8 now reads: 

\v 8 Goliath stood there and shouted to the Israelite army, "Why are you all lined up for battle? You can see that I am a Philistine soldier who is ready to fight?  I can see that you are just the slaves of Saul. Choose one man who can fight for all of you and send him down here to me!

**Comment by SusanQuigley** [comment]
Tom, that looks better, except that there should be no question mark. Also, I don't think this needs "I can see". If we need to have "see" at all, could it be like this? 

You can see that I am a Philistine soldier who is ready to fight and you are just the slaves of Saul.

**Comment by hmw3** [comment]
Is the Why question for information? Otherwise "Y'all shouldn't be lined up for battle, because I'm gonna whup you."

________________________________

**Comment by SusanQuigley** [comment]
I'll write a note explaining that he said it to mock them.

**Comment by TomWarren** [comment]
The why is following the לָ֥מָּה, and that's all there is to it. 
Fun.

**Comment by TomWarren** [comment]
It now reads: 

\v 8 Goliath stood there and shouted to the Israelite army, "Why are you all lined up for battle? You can see that I am a Philistine soldier who is ready to fight and you are just the slaves of Saul. Choose one man who can fight for all of you and send him down here to me!

**Comment by SusanQuigley** [comment]
Thank you.

**Comment by pjoakes** [comment]
Henry is right - the “Why” question is rhetorical and should be unpacked in the UDB along the lines that he suggested (but perhaps not so colloquially).
Thanks,

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Nov 16, 2016, at 1:39 AM, Henry Whitney <notifications@github.com<mailto:notifications@github.com>> wrote:

Is the Why question for information? Otherwise "Y'all shouldn't be lined up for battle, because I'm gonna whup you."

________________________________

**Comment by TomWarren** [comment]
I reworked the UDB for 1SA 17:8, it now reads:
\v 8 Goliath stood there and shouted to the Israelite army, "I can see you are lined up for battle, but you will not fight me. You can see that I am a Philistine soldier who is ready to fight and you are just the slaves of Saul. Choose one man who can fight for all of you and send him down here to me!

**Comment by pjoakes** [comment]
Thanks, Tom.

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Nov 21, 2016, at 8:37 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


I reworked the UDB for 1SA 17:8, it now reads:
\v 8 Goliath stood there and shouted to the Israelite army, "I can see you are lined up for battle, but you will not fight me. You can see that I am a Philistine soldier who is ready to fight and you are just the slaves of Saul. Choose one man who can fight for all of you and send him down here to me!
