### ISSUE TITLE
MRK 15:16 UDB courtyard of the barracks

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#157]
**UDB** The soldiers took Jesus into the courtyard of **the barracks**

Though the barracks may have been in the Praetorium, I don't see any other  versions that speak directly of the barracks.

Could it be changed to something like one of these?
The soldiers took Jesus into the courtyard of the governor's residence
The soldiers took Jesus into the courtyard of the palace
The soldiers took Jesus into the courtyard of the governor's headquarters

**Comment by pohlig** [comment]
Mark uses the word "Praetorium," which was the headquarters and barracks of the Roman cohort that was permanently stationed in Jerusalem. Pilate normally resided in Caesarea, but would stay in the Praetorium when he visited Jerusalem, as at the Passover, for example. 
Unless we go with "Praetorium," I think that "barracks" is the most functionally useful translation. "Palace" does not suggest itself as a reasonable equivalent, and "governor's headquarters" does not suggest why the soldiers would have taken Jesus there, whereas "barracks" suggests that this is where the soldiers made their home and where they amused themselves. I think the rendering should stay put.

**Comment by SusanQuigley** [comment]
**ULB**: The soldiers led him inside the **courtyard (that is, the governor's residence),**
**UDB**: The soldiers took Jesus into the **courtyard of the barracks**

Would you want to change the ULB, or should I write a note similar to what you wrote above?

**the courtyard (that is, the governor's residence)** - The phrase in parentheses clarifies which courtyard they took him to. There were also barracks there for the Roman soldiers to live in. AT: "the courtyard of the governor's residence" or "the courtyard of the soldiers' barracks"

**Comment by TomWarren** [comment]
ULB (not the UDB) of MRK 15:16 now reads:
\v 16 The soldiers led him inside the courtyard (which is the government headquarters), and they called together the whole cohort of soldiers.
