### ISSUE TITLE
GAL 5:3 UDB "His" to "his"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#16]
Gal 5:3 UDB If you expect God to declare you good in **His** sight
The "H" in "His" should be lowercase.

**Comment by hmw3** [comment]
I'll get it. I'm starting work on Gal now.

________________________________

**Comment by SusanQuigley** [comment]
Thank you.

**Comment by hmw3** [comment]
Actually, someone didn't. It was verse 4. Now it's fixed.


________________________________

**Comment by SusanQuigley** [comment]
You're right. Initial verse of chunk was 3. Thanks for fixing it.
