### ISSUE TITLE
Gen 1:21 UDB  swims and swarms

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#160]
Gen 1:21 and every other kind of creature that **swims and swarms** in the water

Some translators had trouble understanding "swarms" as a verb. Could the UDB be changed so it does not include this word? Maybe something like one of these?

and every other kind of creature that swims in large groups in the water 
OR
and every other kind of creature that gathers in large groups and swims in the water

Question. I based my suggestions for the UDB on a definition of the English word "swarm." Is the text really talking about creatures that swarm by swimming together in large groups, or is the Hebrew idea more general, simply meaning that there are huge numbers of them? If it is the more general idea of being many, maybe something like one of these would work for the UDB.

and every other kind of creature that swims in the water and of which there are many
OR 
and every other kind of creature that swims and that the water is full of
OR
and many of every other kind of creature that swims in the water
OR
and every other kind of creature that the water is full of   (This is for if "swim" is not important.)

Once I know what is really intended, I'll write a translation note explaining the ULB uses of the word ("the water swarms with swarms of every living creature")

**Comment by TomWarren** [comment]
I reworked the UDB with the issues in mind, hope this helps:

The UDB of GEN 1:21 now reads: 

\v 21 So God created the very large creatures that live in the sea, and he created all the other living things that are found, in very great numbers, in the waters. He also created every kind of bird that has wings. God looked at all that he had made and he was pleased with them.

**Comment by SusanQuigley** [comment]
Thank you. 
I see that it no longer  has "and he made every kind reproduce itself." I don't know if it is an oversight or intentional.

**Comment by TomWarren** [comment]
According to their kind seemed like a phylum / familial identification term, not reproduction, per se. 
See if this works:

\v 21 So God created the very large creatures that live in the sea, and he created all the other living things that are found, in very great numbers, in the waters, and these creatures would be able to produce their own offspring. He also created every kind of bird that has wings. God looked at all that he had made and he was pleased with them.

Thanks, 
TW

**Comment by SusanQuigley** [comment]
Looks good. Last comment. If the offspring phrase  is put near the end, it could apply to both the sea creatures and the birds. 

So God created the very large creatures that live in the sea, and he created all the other living things that are found, in very great numbers, in the waters. He also created every kind of bird that has wings. All these creatures would be able to produce their own offspring. God looked at all that he had made and he was pleased with them.

**Comment by TomWarren** [comment]
Quite right. Good. 
How about this?
\v 21 So God created the very large creatures that live in the sea, and he created all the other living things that are found, in very great numbers, in the waters. He also created every kind of bird that has wings. All these creatures would be able to produce their own offspring. God looked at all that he had made and he was pleased with them.

**Comment by SusanQuigley** [comment]
Looks great, Tom. Thanks. Hopefully that will be easier for the translators

**Comment by TomWarren** [comment]
Good. Thanks, Susan.
