### ISSUE TITLE
ISA 18:5  UDB the army of Ethiopia?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#161]
UDB: **But even before the army of Ethiopia starts to attack**

The UDB follows the TFT and indicates that the grape vines that grow and that God will cut down represent the Ethiopian army. According to Young's and Oswalt's commentaries, it is the Assyrian army.

Could the UDB be more general by changing "the army of Ethiopia" to "the army"?

**Comment by TomWarren** [comment]
Looks like the "land of Cush" vs 1 is where the Ethiopians were suggested. 
Give this a look. 
I have taken the "he" as the "farmer" in this figure. 

\v 5 I will take action against Ethiopia, just like the farmer knows when it is 
time for the harvest, I will know when the time is right for me to take action. 
\q2 The farmer knows when the grapes flower with blossoms and when those grapes are ripe, even so, I watch the Ethiopians, and I know the right time when the Assyrians will attack them.  
\q1 Just as the farmer cuts off the new growth that robs the tree of its ability to make the best fruit, 
\q2 even so will I take action against the Ethiopians, 
\q2 and Assyria will destroy them to keep them from growing strong again.

**Comment by SusanQuigley** [comment]
I'm not sure. We wondered if the TFT was explaining more than we know. This seems to explain more than the TFT. I wonder if it would be good to prune it back a bit.

**Comment by TomWarren** [comment]
Ok. Try this:
\v 5 Just like the farmer knows when it is time for the harvest, I will know when the time is right for me to take action. 
\q2 The farmer sees the grapes vines making blossoms, just like I watch for the day when the Assyrians will attack Ethiopia.  
\q1 The farmer cuts off the new growth that keeps the tree from growing strong, 
\q2 as the farmer cuts off the new growth, I will take action against the Ethiopians, 
\q2 and clear them away like the farmer cuts off the shoots of the tree.

**Comment by SusanQuigley** [comment]
I think that's better. I'm having trouble keeping the images and armies straight.

**Comment by TomWarren** [comment]
The farmer takes certain actions, and Yahweh mirrors those actions. Easy peezie.

**Comment by SusanQuigley** [comment]
Yeah, right. :)

**Comment by TomWarren** [comment]
Pretty sure, the "he" was "the farmer"

**Comment by SusanQuigley** [comment]
And the blossoming vine whose flowers ripen into grapes is the Assyrian army?

**Comment by SusanQuigley** [comment]
Hi Tom.  How about something like this? I did not tell which army would attack Ethiopia because Assyria is not mentioned in the text. Apparently it's from a knowledge of history that we surmise that the enemy army would be Assyria. 

4. Listen because Yahweh has told me this: 
"I will watch quietly from where I live. 
I will watch quietly like the heat that shimmers as it rises on a summer day.
I will work effectively like the cloud of mist that settles during the heat of harvest.
5. Before the harvest, the farmer sees the grapevines making blossoms and the flowers growing into grapes, and he knows that the time is right to cut off the new growth and spreading branches that keep the tree from growing strong.
In the same way I know when the time is right to take action against Ethiopia, and I will send an army to attack Ethiopia.

**Comment by TomWarren** [comment]
Good work!
The UDB of ISA 18:4-5 now reads:

\v 4 Listen because Yahweh has told me this:
\q2 "I will watch quietly from where I live.
\q1 I will watch quietly like the heat that shimmers as it rises on a summer day.
\q2 I will work effectively like the cloud of mist that settles during the heat of harvest.
\v 5 Before the harvest, the farmer sees the grapevines making blossoms and the flowers growing into grapes, 
\q2 and he knows that the time is right to cut off the new growth and spreading branches that keep the tree from growing strong.
\q1 In the same way I know when the time is right to take action against Ethiopia, and I will send an army to attack Ethiopia. 

The quotation is closed at the end of verse 7.

**Comment by SusanQuigley** [comment]
Thanks, Tom. I'll fix the notes to fit.
