### ISSUE TITLE
Heb 1:5 UDB vs ULB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#165]
And he said in another scripture passage,
"I will be his Father,
and he will be my Son."

The UDB interprets this quote as if it is simply something that God said about his Son.
The ULB interprets it as if it is imbedded in a rhetorical question about what God has never said about an angel.
Maybe the UDB could make it explicit that the point of mentioning this quote is to say that it is not something that God ever said about an angel, but only about his Son.

And he never said about any angel what he said in another scripture passage about his Son:
"I will be his Father,
and he will be my Son."

**Comment by hmw3** [comment]
Suggestion taken.

**Comment by SusanQuigley** [comment]
Thank you.
