### ISSUE TITLE
Pro 27:9 UDB the sweetness of a friend is more important than his advice.

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#167]
The aroma of perfume and the scent of incense can help to make a person feel happy;
the sweetness of a friend is more important than his advice.

Please see my note about the second line in the ULB:
https://github.com/Door43/ulb-en/issues/416

If you change the  ULB, please change this so that it has the same meaning.
Also, it would be good to write this without the metaphor of "sweetness." (which I think represents goodness, kindness, or pleasantness -  I'm not sure which.)

Some ideas for the second line:
and so does the goodness/kindness of a friend's advice
or
and a friend's advice is pleasant/kindness.

**Comment by hmw3** [comment]
I like your first idea best. Let's see how it pans out!

**Comment by SusanQuigley** [comment]
Thanks for doing this. My first suggestion here is meant to match my first suggestion for the ULB issue, and my second suggestion here is mean to match my second suggestion for the ULB.

The first one for both says that a friends advice makes a person happy (like perfume does), while the second suggestion does not imply the simile.

**Comment by hmw3** [comment]
I hope I got things far enough in the right direction that a tN will carry it the rest of the way.

________________________________
