### ISSUE TITLE
PRO 21:1

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#168]
Thank you so much for submitting a suggested change. We ask that you title the issue starting with the 3 letter code of the book followed by the chapter number colon then verse number(s).

For example: MAT 5:6

**Comment by kim-putter** [comment]
2nd line:
whoever lets alcohol lead them to where they get lost, are not wise.

Subject verb agreement is off.

**Comment by hmw3** [comment]
Not only that, there shouldn't be a comma there. Fixed, thanks!

The issue is actually in 20:1.
