### ISSUE TITLE
1Ki 15:34 UDB "his father" to "Jeroboam"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#173]
1Ki 15:34 UDB He did many things that Yahweh said were evil, and his behavior was sinful like **his father's** had been,  and he induced the people of Israel to sin.

The Hebrew says "Jeroboam," not "his father."
Jeroboam was not Baasha's father.

**Comment by TomWarren** [comment]
The UDB of 1KI 15:34 now reads: 

\v 34 Baasha did many things that Yahweh said were evil, and he lived a sinful life just like Jeroboam lived. Baasha's sinful life set an example for the people of Israel that encouraged them to commit sins that were like his sins. 

Hope that covers it. 
TW
