### ISSUE TITLE
1ki 16:34 "because they obeyed"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#174]
He laid the foundation of the city with the loss of Abiram his firstborn, and constructed the gates of the city with the loss of his youngest son Segub, and **they did this because they obeyed** the word of Yahweh, which he had spoken by Joshua son of Nun.

I don't think "they did this because they obeyed" is right. 
Hiel's sons's died because God had said that if anyone rebuilt Jericho, his sons would die. Joshua 6:26.

Could **they did this because they obeyed** be changed to "according to"?

**Comment by TomWarren** [comment]
The ULB of 1KI 16:34 now reads:
\v 34 During Ahab's rule, Hiel of Bethel rebuilt Jericho. Hiel laid the foundation of the city, at the cost of the life of Abiram his firstborn son; and Segub, his youngest son, lost his life while he was building the gates of the city, in keeping with the word of Yahweh which he spoke by Joshua son of Nun.
