### ISSUE TITLE
2Ki 15:1 began the reign of

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#175]
In the twenty-seventh year of Jeroboam king of Israel, **began the reign of** Azariah son of Amaziah king of Judah.

Could this be changed to something like this?

In the twenty-seventh year of Jeroboam king of Israel,  Azariah son of Amaziah king of Judah _began to reign_.

**Comment by TomWarren** [comment]
I edited this chunk a bit for clarity and simplicity.
The ULB of 2KI 15:1-3 now reads: 

\v 1 In the twenty-seventh year of Jeroboam king of Israel, Azariah son of Amaziah king of Judah began his reign.
\v 2 Azariah was sixteen years old when he began to reign, and he reigned for fifty-two years in Jerusalem. His mother's name was Jechiliah, and she was from Jerusalem.
\v 3 He did what was right in the eyes of Yahweh, just as his father Amaziah had done.

Thanks, 

TW
