### ISSUE TITLE
2ki 15:1 UDB Amaziah son of King Amaziah 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#176]
**Amaziah** son of King Amaziah 

The first name should be Azaraiah.

**Comment by TomWarren** [comment]
Azariah ...

The UDB now has:
\v 1 After Jeroboam had been ruling Israel for almost twenty-seven years, Azariah son of Amaziah of Judah, began to rule.

Check ....

Cp ULB has: 
\v 1 In the twenty-seventh year of Jeroboam king of Israel, Azariah son of Amaziah king of Judah began his reign.

Good, 

Thanks,

TW
