### ISSUE TITLE
2ki 15:6 UDB  "Israel" to "Judah"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#178]
2ki 15:6 UDB   it is written in the Book of the Events of the Kings of **Israel**

"Israel" should be "Judah"

**Comment by TomWarren** [comment]
2KI 15:6 now reads:
\v 6 If you want to know about everything else that Azariah did, it is written in the Book of the Events of the Kings of Judah.

Also found this mistake in 
2KI 12:19
2KI 15:36
2KI 16:19
2KI 23:22 (UDB had kings of Judah and Israel, implying that the kings ruled simultaneously (or some other joint venture) - changed to kings of Judah and kings of Israel)
1CH 17:12 had an odd rendering for "establish his throne forever" and this was changed to read: **And I will make the rule of one of his descendants so strong that it will last forever.**
ICH 28:4 - the UDB was convoluted. The revision makes it clear without using "house of Judah and house of Israel" in a summary sense. It now reads: 
**But Yahweh, the God to whom we Israelites belong, had chosen me and my descendants to be the kings of Israel forever. First he chose Judah to be a leader, and from the people of Judah he chose me to be the king over all of Israel.**
2CH 28:27 now reads: \v 27 Ahaz died and was buried in Jerusalem, but he was not buried in the tombs where the other kings **of Israel** had been buried. Then his son Hezekiah became the king. (BOLD is added).
2CH 35:26-27 the UDB reversed "Israel and Judah" in the former version it had "Judah and Israel"; it now reads:
\v 26-27 A record of the other things that happened while Josiah ruled, from the time he started to rule until he died, including how he faithfully was devoted to honoring God by obeying all that was written in the laws of Yahweh, is written in the Book of the Kings of Israel and Judah.
