### ISSUE TITLE
Acts 2:30 ULB

### ISSUE THREAD

**Issue by TomWarren** [Door43/udb-en#18]
There had been a lot of conversation on Acts 2:30. I wanted to open an issue on it. 
**\v 30 Therefore, he was a prophet and knew that God had sworn with an oath to him, that he would set one of his descendants upon his throne.**

I have returned the rendering to "one of his descendants" which follows almost all modern translations.

Avoiding the difficult "one of the fruit of his loins" or the indiscrete "one of the fruit of his genitals" (which we all agree is objectionable). 
Loins is a euphemism, or it is inaccurate. 
Genitals is offensive.
Descendants points to the genetic aspect ("genitals") and the offspring of David.But moves away from the figure of speech "fruit of his loins/genitals". 

This is the only "fruit of his loins" that had occurred in the ULB. 

Is there a better rendering than "one of his descendants"?

The more opaque the figure, the more difficult to present it.

**Comment by lrsallee** [comment]
I personally do no like the use of the archaic "fruit of his loins" and much, much prefer "one of his descendants." 

My (minimal) understanding of this current issue is that Perry would like as many figures as possible to remain in the ULB so they can reference them in the checking/core tool the are developing. It seems to me that using the original FOS here would sacrifice understanding in favor of having fuller tool results. But we will develop a TN to work around whatever the text team decides.

**Comment by lrsallee** [comment]
BTW, this is about the ULB, but is in the UDB issue section. That might be confusing to some.

**Comment by TomWarren** [comment]
I will move it to ULB. Haven't done' this much.
