### ISSUE TITLE
2ki 16:3 UDB  "drive" to "forced"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#180]
UDB: people whom Yahweh had **drive** out 

"drive" should be "driven"
Or could "drive" be changed to "forced"?
I expect that when MTTs see the word "drive' they will think of driving a car.
Maybe it would be good if "drive" was limited to driving a chariot.

**Comment by TomWarren** [comment]
The UDB of 2KI 16:3 now reads:
\v 3 Instead, he was as sinful as the kings of Israel had been. He even sacrificed his son to be an offering to idols. That imitated the disgusting things that the people who previously lived there had done, people whom Yahweh had **driven** out as the Israelites were advancing through the land.
