### ISSUE TITLE
NEH 4:17 mismatch

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#181]
UDB: "The leaders stood behind those who were building the wall and those who carried the heavy loads on their backs..."

ULB: "And so the same workers who were building the wall and carrying loads were also guarding their positions..."

**Comment by TomWarren** [comment]
The UDB had taken a phrase from vs 16 and rolled it into 17. 
The UDB of NEH 4:17 now reads:
\v 17 Those who were building the wall and those who carried the heavy loads on their backs, all of them built the wall with one hand and held a weapon in the other hand.
