### ISSUE TITLE
Ezr 7:22 UDB missing space

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#182]
Ezr 7:22 UDB Give him up to 3 and one-halfmetric tons

A space is needed before "metric."
Should "3" be "three"?

**Comment by TomWarren** [comment]
Space added:
UDB of EZR 7:22 now reads:

\v 22 Give him up to 3 and one-half metric tons of silver, five hundred bushels of wheat, two and one-fifth kiloliters of wine, the same of olive oil, and all the salt that they need.

Thanks,

Tom
