### ISSUE TITLE
Job 19:28 UDB Question or exclamation

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#187]
ULB: How we will persecute him!
UDB: What more can we do to cause him to suffer?

ULB translates it as an exclamation. 
UDB translates it as a question. 
If it really is a rhetorical question, it would be good to have the question in the ULB and the exclamation in the UDB.
 If it's not a question, it would be good to change the UDB to either an exclamation or a statement such as 
We will certainly cause him to suffer
or
We will cause him to suffer severely

**Comment by TomWarren** [comment]
The UDB of JOB 19:28 now reads: 
\v 28 If you three men say, 'This is how we will cause him to suffer!'
\q2 and you say, 'He is the one who has caused his own troubles,'

More of a statement, here, than a question.
