### ISSUE TITLE
HOS 10:12  typo

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#188]
Hos 10:12  Do the hard **word** of breaking up the unplowed ground
It looks like **word** should be **work**

**Comment by TomWarren** [comment]
The UDB of HOS 10:12a now reads:
\v 12 Plow, now, and do what is right,
\q2 and you will reap the fruit of faithful love.
\q1 Do the hard **work** of breaking up the unplowed ground,

Thanks,
TW
