### ISSUE TITLE
Luk 12:33 UDB - definition of "poor"

### ISSUE THREAD

**Issue by lrsallee** [Door43/udb-en#19]
This is an old note about a text change that was not addressed:

Is UDB “those who do not have as much as you do” really the proper interpretation of ULB “poor,” or would it be something more like “those who do not have food and clothing” or “those who do not have what they need”?

**Comment by TomWarren** [comment]
Edited UDB Luke 12:33
\v 33 So now sell the things that you own. Give the money to those who do not have the food and clothing they need or a place to live. Get yourselves wallets that do not wear out, and you will store up treasure in heaven where it will always be safe. There, no thief can come near to steal it, and no moths can destroy your clothing.

Note that "termites" were returned to "moths" following the ULB.
