### ISSUE TITLE
Job 27:1 UDB  replied

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#191]
27:1 UDB: Job **replied** to his three friends by saying this:

The word "replied" might give the impression that one of Job's 3 friends was the speaker in the previous verses. But Job was the speaker through all of ch 26. (You corrected Job 26:5 so that it was Job speaking rather than Bildad.)

Could 27:1a  be changed to something like this?
Job continued speaking to his three friends.

**Comment by TomWarren** [comment]
Yes, that is an improvement.
The UDB of JOB 27:1 now reads:
\v 1 Job continued speaking to his three friend:
