### ISSUE TITLE
Job 27:2-3 ULB not a sentence

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#192]
27:2-3 "As God lives, who has taken away my justice,
the Almighty, who made my life bitter,
as long as my life is yet in me
and breath from God is in my nostrils.

We have two verses starting with "as", but nothing to finish up the sentence.
Other versions have verse 4 as the end of the sentence. (V2 introduces the oath, v3 is a time phrase within the oath, and v4 finishes  the first sentence of his oath.)

Ideally v3 would end with a comma rather than a period.
But if we don't want sentences to cross chunks, maybe something like this could be added to the end of verse 3:
this is what I promise.

**Comment by TomWarren** [comment]
This is how we have handled the "across the chunk" sections in similar cases: 

\v 1 Job resumed speaking and he said,
\q
\v 2 "As surely as God lives, who has taken away my justice,
\q the Almighty, who made my life bitter,
\q
\v 3 for while my life is yet in me,
\q and the breath from God is in my nostrils, 
\q this is what I will do.

\s5
\q
\v 4 My lips will not speak wickedness,
\q neither will my tongue speak deceit;
\v 5 I will never admit that you three are right;
\q until I die I will never deny my integrity.

Note: "three" is added for clarity. The "you" is plural and refers to Job's friends.

**Comment by SusanQuigley** [comment]
\v 2 "**As** surely as God lives, who has taken away my justice,
\q the Almighty, who made my life bitter,
\q
\v 3 **for** while my life is yet in me,
\q and the breath from God is in my nostrils,
\q this is what I will do.

Could the word "for" at the beginning of v3 be removed. The conjunction "for" only fits following an independent clause. V2 is not independent because it starts with "As." The only independent clause in these two verses is "this is what I will do."

**Comment by TomWarren** [comment]
I noted that some other translations had "For" there, and I fell for it. 
The ULB of JOB 27:2-3 now reads: 

\v 2 "As surely as God lives, who has taken away my justice,
\q the Almighty, who made my life bitter,
\q
\v 3 while my life is yet in me,
\q and the breath from God is in my nostrils, 
\q this is what I will do.

There it is.

TW

**Comment by SusanQuigley** [comment]
Thank you, Tom.
