### ISSUE TITLE
Job 25:5 UDB vs ULB One or two groups?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#193]
ULB: The dead tremble under the waters,
and those who dwell in them.

UDB: Because the spirits of dead people are afraid,
they tremble in the waters that are deep under the earth.

The ULB speaks of two groups of people: 1) the dead who are under the waters, and 2)  those who dwell in the waters.
The UDB speaks of one group of people: the spirits of dead people who are in the waters

**Comment by TomWarren** [comment]
The ULB now reads:
\v 5 The dead are made to tremble,
\q those beneath the waters,
\q and all who dwell in them.

The UDB now reads:
\v 5 The spirits of dead people tremble with fear,
\q2 and along with them those who are under the waters, 
\q1 and everyone who dwells with them. 

Hope that covers it. Tough section.

Tom

**Comment by SusanQuigley** [comment]
Yes, this is tough.
Now the UDB seems to refer to 3 groups of people.
I'm not sure if the ULB refers to 2 or 3 groups. Does "those beneath the waters" tell us something about the dead in the first line, or is it a second group?

**Comment by SusanQuigley** [comment]
\v 5 The dead are made to tremble,
\q those beneath the waters,
\q and all who dwell in them.

The UDB now reads:
\v 5 The spirits of dead people tremble with fear,
\q2 and along with them those who are under the waters,
\q1 and everyone who dwells with them.

I just realized that perhaps the comma after "waters" is throwing me off. 
ULB: If the comma after "waters" is removed, then "those beneath the waters and all who dwell in them" are two groups of  the "dead" in the first line.
UDB: If the comma after "waters" is removed, then there is no significant difference. "those who are under the waters and everyone who dwells with them" are two groups that tremble along with  the dead in the first line.

**Comment by TomWarren** [comment]
Let's say three groups:
ULB: JOB 26:5 ... 
\v 5 The dead are made to tremble,
\q and those who are beneath the waters,
\q along with all who dwell in them.

UDB was not changed:
\v 5 The spirits of dead people tremble with fear,
\q2 and along with them those who are under the waters, 
\q1 and everyone who dwells with them. 

Try that.

**Comment by SusanQuigley** [comment]
Ok. Thanks

**Comment by TomWarren** [comment]
I like your way better:
ULB:
\v 5 The spirits of dead people tremble with fear,
\q2 with those who are under the waters 
\q1 and everyone who dwells with them. 


UDB:
\v 5 The dead are made to tremble,
\q those who are beneath the waters
\q and all who dwell in them.

Try this.

**Comment by SusanQuigley** [comment]
It looks like ULB and UDB still don't quite match. 
Would you want to delete the word "with" in line 2?
That way for both versions lines 2 and 3 would explain who the dead are in line 1.

**Comment by TomWarren** [comment]
I edited that out in the space between our Githubs.

Should be ok.
