### ISSUE TITLE
Job 26:9 ULB "the face of the moon"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#195]
Job 26:9 ULB He encloses the face of the moon

Would you want to change "face" to "surface"? 

Tom, this is a minor issue. If you don't want to make the change at all, that's 
If you want to make the change, but not till after March 31, you can label it as Maintenance Mode.

**Comment by TomWarren** [comment]
Change face to "surface" right?
There were about 8 or 9 of these.

**Comment by SusanQuigley** [comment]
Thanks, Tom. I want to write a note but the ULB still isn't showing up in the USFM file or Door43. 
Is this what 26:9a looks like now?
He encloses the surface of the moon

**Comment by TomWarren** [comment]
The ULB of JOB 26:9 now reads:
\v 9 He covers the surface of the moon
\q and spreads his clouds on it.
