### ISSUE TITLE
Job 26:13 ULB Typo

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#196]
ULB: 
By his breath, **he cleared the heavens of storms;** 
**the heavens were cleared of storms;**
his hand pierced the fleeing serpent.

UDB: 
By his breath he caused the sky to be bright;
by his hand he killed the great dragon in the sea as it was fleeing from him.

ULB: It looks like one of these was supposed to be deleted: "he cleared the heavens of storms" or "the heavens were cleared of storms"

**Comment by TomWarren** [comment]
The ULB of JOB 26:13 is corrected. 
It now reads:
\v 13 By his breath he cleared the heavens of storms; 
\q his hand pierced the fleeing serpent.

Thanks,
 
TW

**Comment by TomWarren** [comment]
Better, the ULB now reads:

\v 13 By his breath he made the skies clear; 
\q his hand pierced the fleeing serpent.

The UDB can stand. 

Sorry, assumed all was well and then checked the source. 

There it is. 

TW
