### ISSUE TITLE
Job 28:17b "jewels" or "vases"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#197]
ULB: neither can it be exchanged for **jewels** of fine gold.
UDB: worth more than **vases** made from fine gold.

ULB has "jewels" and UDB has "vases." Would you want them to be the same?

**Comment by TomWarren** [comment]
The UDB now reads: 
\v 17 It is worth much more than gold or beautiful quartz;
\q2 wisdom is more expensive than the finest jewels, and it is worth more than a vase made with pure gold.

Best to keep them aligned in meaning, where we can. 
Thanks,
TW

**Comment by SusanQuigley** [comment]
Tom, did you intend for the UDB to have both "jewels" and "vases" in 17b? 17b in the ULB has only "jewels", and the Hebrew seems to refer to only one thing: utəmuratah kəli paz

**Comment by TomWarren** [comment]
My UDB effort was to show there was both jewels (vessels, vases) and gold, "jewels of gold", and most would think that it would be some piece of gold with jewels in it, and that it was not just a piece of gold that was called a jewel. The last phrase reads to me, "its worth is that of a vessel (כְּלִי) of fine gold." The vessel is my rendering of "vase."  The ESV renders "jewels" for "vessels" (also NIV).

The UDB of JOB 28:17 now reads: 
\v 17 It is worth much more than gold or beautiful quartz;
\q2 wisdom is more valuable than the finest containers that are made with pure gold.

Try that.
Thanks,
Tom

**Comment by SusanQuigley** [comment]
The ULB has "jewels of fine gold." 
Should I understand ULB's "jewels" to refer to the UDB's "finest containers"? 
Should I understand both to refer to vases or to pieces of gold jewelry that contain jewels?

**Comment by TomWarren** [comment]
I shortened down my first reply. It could be misunderstood as jewels. It think container, vase, is the idea. The thing I was trying to avoid was gold as jewels. Just doesn't work. I could take it either way, it is gold that contains jewels, or it is a container of gold. I think the container of gold may be more on target. But there is a little difference, in that the point is not the gold or the container, but the comparison with wisdom. 
Thanks,
Tom
