### ISSUE TITLE
Job 29:18-20

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#198]
UDB: At that time I thought, 'Surely I will live in peace until I am very old,
and I will die at home with my family.'
19I was like a tree whose roots reach down into the water
and whose branches become wet with dew each night.
20People always honored me,
and I was always strong like a new bow. 

ULB
18Then I said, 'I will die in my nest;
I will multiply my days like the grains of sand.
19My roots are spread out to the waters,
and dew lies all night on my branches.
20The honor in me is always fresh,
and the bow of my strength is always new in my hand.

The ULB has present tense starting in the quote in v18 and going through the end of v20.
The UDB has present tense only in the quote in v18, but not through 19 and 20. 

Could the UDB be changed to this? I have moved the final quote mark to the end of v20 and changed the tense in 19 and 20 to present.
At that time I thought, 'Surely I will live in peace until I am very old,
and I will die at home with my family.
19I **am** like a tree whose roots reach down into the water
and whose branches become wet with dew each night.
20People always **honor** me,
and I **am** always strong like a new bow.**'**

**Comment by TomWarren** [comment]
Seems right. The UDB of JOB 29:18-20 now reads:
\v 18 At that time I though**_t, 'S_**urely I will live in peace until I am very old,
\q2 and I will die at home with my family.
\q1
\v 19 I am like a tree whose roots reach down into the water
\q2 and whose branches become wet with dew each night.

\s5
\q1
\v 20 People always honor me,
\q2 and I am always strong like a new **_bow.'_**

**Comment by SusanQuigley** [comment]
Thank you.
