### ISSUE TITLE
DAN 3:29

### ISSUE THREAD

**Issue by TomWarren** [Door43/udb-en#2]
The continuity of dunghill and related terms, ash heap.

Dear Henry,

Here is my effort on the smelly issue.

There were two "dunghills" in the UDB. Dung us still used in the UDB, much like manure.

Isa 25:10 reworked;  TN checked no changes made. This is "dunghill," but it is really a pit.

\q1
\v 10 For on this mountain the hand of Yahweh will rest;
\q1 and Moab will be trampled down in his place, even as straw is trampled down in pit filled with manure.

This is rendering "ash heap" correctly, not a dunghill.
1SA 2:8 ULB changed;  TN updated to "ash heap"
\v 8 He raises up the poor out of the dust.
\q He lifts the needy from the ash heap  [this is a better rendering]
\q to make them sit with princes
\q and inherit the seat of honor.
\q For the pillars of the earth are Yahweh's
\q and he has set the world upon them.

 The word for pile of refuse: Often translated dunghill in some translations. But the lexicon holds that it is a pile of junk/ refuse / liking "pile of garbage".
 נְוָלוּ  Here is your consistency issue; Is used in:

ULB changed; UDB ok; TN ok.
EZR 6:11  \v 11 I am ordering that if anyone violates this decree, a beam must be pulled from his house and he must be impaled on it. His house must then be turned into a pile of garbage because of this.

ULB changed; UDB ok; TN note "dunghill" removed.
DAN 2:5  \v 5 The king replied to the wise men, "This matter has been settled. If you do not reveal the dream to me and interpret it, your bodies will be torn apart and your houses made into piles of garbage."

ULB changed; ULB changed; TN not changed.
DAN 3:29 \v 29 Therefore I make a decree that any people, nation, or language that speaks anything against the God of Shadrach, Meshach, and Abednego must be torn apart, and that their houses must be made into piles of garbage because there is no other god who is able to save like this."

UDB, they will be torn to pieces and their houses will be torn down and made into piles of garbage.

More work may need to be done. 
Sincerely yours ,

Tom

**Comment by hmw3** [comment]
And yes, thank you for your work on this.


________________________________
