### ISSUE TITLE
JOb 31:16-18 UDB Whose youth?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#200]
UDB: **16-18** I have guided orphans from the time **that they were born**;
I have taken care of them since **they were young**.

ULB : **18**because **from my youth** the orphan grew up with me as with a father,
and I have guided his mother, a widow, **from my own mother's womb.**

The ULB matches other versions in referring to Job's youth in both phrases.
The UDB refers to the orphans' youth.

Suggested change to UDB.
From the time I was young I have taken care of orphans;
All my life I have guided their widowed mothers. 
or 
From the time I was young I have taken care of orphans;
All my life I have guided widows.

**Comment by TomWarren** [comment]
The UDB of JOB 31:16 now reads: 
Bridge verse \v 16-18 From the time I was young I have taken care of orphans;
All my life I have never given the widowed mothers a reason to lose hope.

I worked through it again. Hope that helps. 

Thanks Susan, 

Tom
