### ISSUE TITLE
Act 27:1 Imperial or Augustan?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#201]
ULB: the Imperial Regiment.
UDB: a regiment called "the Augustans"

Would you want these to be the same?

I added to the note an said that some versions translate it as "the Augustan Regiment." Maybe that will cover it.

**Comment by TomWarren** [comment]
The UDB of ACT 27:1 now reads:
\v 1 When the Governor decided that we should sail for Italy, he put Paul and some other prisoners into the control of an army captain whose name was Julius. He held the rank of centurion and was part of a large number of soldiers who were under the direct command of the Emperor.

This rendering deals with the complexity of the name of the regiment, I hope. 
Thanks,
Tom
