### ISSUE TITLE
Jer 2:34 UDB But you chose to treat her wickedly

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#205]
UDB Although you have on your clothes the blood of poor people whom you have murdered,
people who were innocent! You did not catch them robbing you, **but you chose to treat her wickedly.**

It looks like "but you chose to treat her wickedly" is implicit info made explicit, but the pronoun "her" is odd. I would expect it to be "them," referring to to the innocent people that they murdered.

**Comment by TomWarren** [comment]
This was resolved in previous ISSUE>
