### ISSUE TITLE
Jer 4:2 UDB "Misplaced Quotes?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#207]
Jer 4:2 UDB
and if you declare, 'Just as surely as Yahweh lives, what he says is true and just,
and he teaches righteous living,'
then the people in the other nations of the world will ask me to bless them as I have blessed you,
and they will all come and honor me."

Most versions treat "in truth, justice, and righteousness" describing how the people swear, not how Yahweh lives.
Could the UDB be changed to something like one of these?

and if you say, "As surely as Yahweh lives" when you take your oaths, 
and if you are truthful, just, and righteous, 
then the people in the other nations of the world will ask me to bless them as I have blessed you,
and they will all come and honor me."

or 
and if you live truthful, just, and righteous lives 
when you take your oaths, saying, "As surely as Yahweh lives," 
then the people in the other nations of the world will ask me to bless them as I have blessed you,
and they will all come and honor me."

**Comment by TomWarren** [comment]
The UDB of JER 4:1-2 now reads: 

\v 1 Yahweh says, "You Israelite people, if you come back to anyone, it should be to me.
\q2 If you get rid of those detestable idols,
\q2 if you do not go away from me again,
\q1
\v 2 and if you declare, 'Just as surely as Yahweh lives,' 
\q1 when you take your oaths, 
\q2 and if you are truthful, just, and righteous, 
\q1 then the people in the other nations of the world 
\q1 will ask me to bless them as I have blessed you,
\q1 and they will all come and honor me."

Thanks,

Tom
