### ISSUE TITLE
Jer 4:11-12  Who is speaking?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#208]
UDB: Yahweh told me that when that happens, **some will say** to the people of Jerusalem,
"A huge army will come to attack you.
They will not be like a gentle breeze that separates the wheat from the chaff.
They will be like a very hot wind that blows in from the desert.
12They will be like a strong blast that _I will send_.
Now I am declaring that _I will punish you_."

ULB: In that time it will be said of this people and Jerusalem, "A burning wind from the plains of the desert will make its way to the daughter of my people. It will not winnow or cleanse them. 12A wind far stronger than that will come at **my command**, and **I will now pass sentence** against them.

I don't see any versions that say that other people would say this. Verse 12 indicates that it must be the Lord speaking. The New Living Translation says that the LORD will say it.
Could **UDB** be changed to something like this?

**When that happens, Yahweh will say to the people of Jerusalem,**
"A huge army will come to attack you.
They will not be like a gentle breeze that separates the wheat from the chaff.
They will be like a very hot wind that blows in from the desert.
12They will be like a strong blast that _I will send_.
Now I am declaring that _I will punish you_."

**Comment by TomWarren** [comment]
Yep. The UDB for JER 4:11-12 now read:

\v 11 When that happens, Yahweh will say to the people of Jerusalem,,
\q1 "A huge army will come to attack you.
\q2 They will not be like a gentle breeze that separates the wheat from the chaff.
\q1 They will be like a very hot wind that blows in from the desert.
\q1
\v 12 They will be like a strong blast that I will send.
\q2 Now I am declaring that I will punish you."

That fits the ULB meaning. 
Thanks,

Tom W

**Comment by SusanQuigley** [comment]
There's an extra comma at the end of the first line.
