### ISSUE TITLE
Invalid USFM tag in Malachi 1:13

### ISSUE THREAD

**Issue by phillip-hopper** [Door43/udb-en#21]
In the English UDB, in Malachi 1:13, there is a `\p2` usfm tag. I believe this should actually be `\pi2`.

**Comment by TomWarren** [comment]
This seemed to even it out in the UDB, Mal 1:13ff

\s5
\pi 
\v 13 You also say, 
\pi2 'We are tired of burning all these sacrifices on the altar.' 
\pi2 You turn up your noses at doing this. You bring sheep or goats that wild animals have attacked and torn in two. You also bring animals that are sick or that cannot walk. You cannot really think that I should accept these from you, can you?" 
\m This is what Yahweh, Commander of the angel armies, says. 

Thanks, 
TW
