### ISSUE TITLE
ECC 5:2

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#211]
"Think carefully before you speak
and do not be too quick to promise God that you will do something."

Traditionally this is translated as "to bring up a matter." Is saying that this specifically implies making a promise too narrow of a translation? Something to consider.

**Comment by TomWarren** [comment]
Here is a go at this section (to bring it into alignment with the ULB.
\v 2 Do not speak too quickly without thinking about the words you say;
\q2 and do not be too quick in your heart to complain about something to God.
\q1 Remember that God is very different from you and he is in heaven. 
\q2 You, however, are very limited and you must live all your life here on earth.
\q1 So think carefully about what you say to God, and do not speak to him without preparing beforehand what you will say. 

That is a try.

Thanks, 

Tom
