### ISSUE TITLE
Jer 5:12 UDB He is not even real - maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#212]
UDB: They have lied about me and said,
**'He is not even real!**
ULB: They have spoken falsely about Yahweh and they said, '**He will do nothing;**

Could the UDB "He is not even real" be changed to fit with the ULB?

**Comment by TomWarren** [comment]
The UDB of JER 5:12 now reads:
\v 12 They have lied about me and said,
\q2 **'He cannot do anything to help us!**
\q2 He will not punish us!
\q2 He will not send disasters on us!
\q2 We will not experience wars or famines!

Thanks,

Tom
