### ISSUE TITLE
Luke 17:37 

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/udb-en#214]
Chunk break between verses 36 and 37 is missing in the UDB.

Cross reference: https://github.com/Door43/ulb-en/issues/731
See: https://github.com/unfoldingWord-dev/door43.org/issues/499

**Comment by TomWarren** [comment]
The UDB at LUK 17:36-37 now has a chunk marker:
\v 35-36 Two women will be grinding grain together; one will be taken and the other left behind."

\s5
\v 37 His disciples said to him, "Lord, where will this happen?" He replied to them, 

Thanks,

Tom
