### ISSUE TITLE
Amo 4:9 UDB be struck and mildew

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#215]
UDB: I caused your grain fields to dry up,
and your gardens and vineyards **to be struck and mildew**.

Could "struck and mildew" be changed to "struck **with** mildew"?

**Comment by TomWarren** [comment]
The ULB of AMO 4:9 was edited, and now reads:
\v 9 Many times I struck your crops with disease and mildew.
\q2 The locusts devoured your gardens and vineyards, 
\q2 your fig trees and olive trees, yet you did not return to me
\q1 —this is Yahweh's declaration."
