### ISSUE TITLE
1Co 8:6 UDB punctuation.  Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#216]
"There is one God, the Father,
from him come all things, and for him we live.
And there is only one Lord, Jesus Christ;
he made everything there is, and he is the one who gives us life."

I think the comma after "Father" should be a semicolon.

**Comment by TomWarren** [comment]
I did wonder about that ... 
The ULB of !CO 8:6 now reads:
\v 6 Yet for us there is only one God, the Father, from whom are all things and for whom we live; and one Lord Jesus Christ, through whom all things exist, and through whom we exist.


Thanks,

Tom

**Comment by hmw3** [comment]
Actually, with the new wording, the semicolon should be a comma. "From whom ... we live" is a relative clause modifying "Father," so the RC should end with a comma. I would also delete the comma after the first "exist."

\v 6 Yet for us there is only one God, the Father [appositive of "God"], from whom are all things and for whom we live [relative clause], and one Lord Jesus Christ, through whom all things exist and through whom we exist [relative clause].

**Comment by TomWarren** [comment]
OK. The ULB of 1CO 8:6 now reads;
\v 6 Yet for us there is only one God, the Father, from whom are all things and for whom we live, and one Lord Jesus Christ, through whom all things exist, and through whom we exist.

Thanks Henry, 

Tom
