### ISSUE TITLE
Amo 5:8 UDB  Question versus statement

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#218]
Amo 5:8 UDB Do you know who created all the groups of stars
and put them in their places?
ULB: God made the Pleiades and Orion;

The UDB translates it as a question. The ULB and the other versions translate it as a statement.

Could the  UDB be changed to something like one of these?
God created the groups of stars and put them in their places.
or
God created the stars and put them in their groups.

**Comment by TomWarren** [comment]
The UDB of AMO 5:8a now reads;
\v 8 God created all the groups of stars
\q2 and he put them in their places.

Thanks Susan, 

Tom
