### ISSUE TITLE
For Tom W

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#22]
Testing Testing...did this work? Did you receive this?

**Comment by TomWarren** [comment]
Awesome. Puts an email, with link here. 
Can edit the post. 
I will close this, but you try to reopen it.

**Comment by kim-putter** [comment]
Got it.

**Comment by TomWarren** [comment]
Trying to figure out how to direct this to individuals.

**Comment by destatez** [comment]
@kim-putter 
Try puting an asterisk in front of the person's name to direct it to them. Like this one to you

**Comment by TomWarren** [comment]
Great!  Thanks


Tom

**Comment by destatez** [comment]
Since you got it, Tim , that means it did not go only to Kim. Oh well!

**Comment by TomWarren** [comment]
Dave,

Just for clarity, does the name go in box where the Reference: Luk 3:13

usually goes, or does it go in the:

chat box

at the beginning of the chat?

And when do you want to start joining the TextTeam?

Thanks,

Tom

**Comment by destatez** [comment]
Tom

  What I tried for the example to Kim, was to put the "@kim-putter " at the start of the message text. I do not think that it worked like it does in Slack, since you got a copy of it, as well. I am not sure he got a copy of it.

On the 2nd topic, I am ready to go. Shall we Skype on the subject?

Dave

**Comment by TomWarren** [comment]
If you will, let me add you to our 4 pm Skype today, and you can see 
what we are up to. Is that OK?

Tom

**Comment by destatez** [comment]
Sure.That's 4 pm ET?

**Comment by kim-putter** [comment]
yes

 how do I connect?

________________________________

**Comment by kim-putter** [comment]
Never mind, you don't need me there. You need Dave. And at 4 I have my notes meeting.


Just let me know what you figure out.

________________________________

**Comment by TomWarren** [comment]
All is well.
