### ISSUE TITLE
Lam 3:22 UDB  Double translation of lo tamnu/tamam -  Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#221]
**UDB**: Yahweh **never stops** faithfully loving us, and because of his love, we are **not destroyed**.
He never stops acting kindly toward us.
**ULB**: The steadfast love of Yahweh never ceases and his compassions never end,

Some early texts have "The steadfast love of the  LORD never ceases" and some have "Because of the steadfast love of the Lord we are not cut off."  It looks like the UDB has both.

**Comment by TomWarren** [comment]
Aligning the UDB with the ULB, the UDB of LAM 3:22 now reads:

\v 22 Yahweh never stops faithfully loving us, and he shows his compassion for us forever.

Thanks Susan, 

Tom

**Comment by SusanQuigley** [comment]
Nice.
