### ISSUE TITLE
Lam 3:31 UDB  Yahweh or Lord - Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#222]
Lam 3:31 **Yahweh** does not abandon us, his people, forever.
Lam 3:36b **Yahweh** certainly sees all these things.
Hebrew has adonai, and ULB (should be UDB) has "the Lord"

**Comment by TomWarren** [comment]
The UDB of LAM 3:31 was already changed to read: The Lord ... 

The UDB of LAM 3:36 now reads:
\v 36 or if they cause judges to decide matters unjustly,
\q2 the Lord certainly sees all these things.

Checking the ULB for 3:31 and 3:36, both have "the Lord" for אֲדֹנָ֖י (adonai).

Thanks, 

Tom
