### ISSUE TITLE
Lam 3:65 UDB does not match ULB - Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#223]
ULB: You will let their hearts be **shameless**! May your condemnation be upon them!
UDB: Curse them and make them **very, very afraid of you**.

Could the UDB be changed to "shameless" or "stubborn"?

**Comment by TomWarren** [comment]
The UDB of LAM 3:65 now reads:
\v 65 You permit them to do whatever they want, 
\q2 and you punish them by taking away their shame,
\q2 that is why your curse is upon them.

Thanks,

Tom

**Comment by SusanQuigley** [comment]
Thanks for fixing the content.
It looks like there should be a period or semicolon after the word "shame" in the UDB.

**Comment by TomWarren** [comment]
Fix
UDB of LAM 3:65 now reads:
\v 65 You permit them to do whatever they want, 
\q2 and you punish them by taking away their shame.
**\q2 That** is why your curse is upon them.

Thanks Susan, 

Tom
