### ISSUE TITLE
LAM 1:17 typo 

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#224]
...Yahweh has give the order that the people in nearby nations
will become the enemies of the descendants of our father Jacob (who are also called the Israelites)...

Above the word "give" should be "given."

**Comment by TomWarren** [comment]
The UDB of LAM 1:17 now reads:
\v 17 The people who lived in Zion (the city of Jerusalem)
\q2 have no one to give them comfort.
\q1 Yahweh **has given the order** that the people in nearby nations
\q2 will become the enemies of the descendants of our father Jacob (who are also called the Israelites).
\q2 Jerusalem has become disgusting to them.

Thanks Kim, 

Tom
