### ISSUE TITLE
Lam 4:6 UDB Who was not rescued? - Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#226]
**UDB**: 6 The people of Sodom died very suddenly in a disaster,
and there was no one to rescue **them**;
but God has punished my people
more severely than the people of Sodom.
7 **Our** leaders were could be compare to snow or milk,
so they were clean and spotless.

**ULB**: The punishment of **the daughter of my people** is greater than that of Sodom,
and it was overthrown in a moment
and no one lifted a hand to help **her**.
7 **Her** leaders were purer than snow, whiter than milk;

In the UDB, it was the people of Sodom who were not helped. 
In the ULB, it looks like it was the "the daughter of my people" (Jerusalem) who was  not helped.
Could the UDB be changed to say that it was the people of Jerusalem who were not helped?
Maybe something like this:

6 The people of Sodom died very suddenly in a disaster.
But God has punished my people
more severely than the people of Sodom,
and there was no one to rescue **us.**
7 **Our** leaders were could be compare to snow or milk,
so they were clean and spotless.

**Comment by TomWarren** [comment]
The UDB of LAM 4:6-7 now reads:

\v 6 The people of Sodom died very suddenly in a disaster.
\q2 But God punished my people
\q2 more severely than the people of Sodom,
\q and there was no one to rescue us.

\s5
\q1
\v 7 Our leaders could be compared to snow or milk,
\q2  they were so clean and spotless.
\q1 Their physical bodies were healthy,
\q2 and their health and strength could compare
\q2 to the brilliance and beauty of sapphires.

Thanks Susan, 

Tom

**Comment by SusanQuigley** [comment]
Thank you for fixing this.  Now that there was also a change to the ULB, I have another concern.

UDB:
\v 6 The people of Sodom died very suddenly in a disaster.
\q2 But God punished my people
\q2 more severely than the people of Sodom,
\q **and there was no one to rescue us.**

ULB:
\v 6 The punishment of the daughter of my people is greater than that of Sodom,
\q which was overthrown in a moment and **no hands were wrung for her**.

The ULB has  "no hands were wrung for her".
The UDB has "and there was no one to rescue us."
For the UDB, would "no one cared about us" or "no one worried about us" be good instead of 
"there was no one to rescue us"? Or should I does no wringing of the hands for Jerusalem imply that no one bothered to rescue her?

**Comment by TomWarren** [comment]
Try this. 
The UDB of LAM 4:6 now reads;
\v 6 The people of Sodom died very suddenly in a disaster.
\q2 But God punished my people
\q2 more severely than the people of Sodom,
\q and no one was concerned about all that we suffered.

Thanks, 

Tom

**Comment by SusanQuigley** [comment]
That's great. Thanks.
