### ISSUE TITLE
Lam 4:7 UDB Typos and odd logic

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#227]
Our leaders **were could be compare** to snow or milk,
**so** they were clean and spotless.
Their physical bodies were healthy,
and their health and strength could compare
to * brilliance and beauty of sapphires.

**Typos**: "were could be compare" and missing "the" before "brilliance."
**Odd logic**:  I think "because" would fit better than "so". 
**Unneeded Complexity:** I don't think the UDB typically uses "compare" for similes.

How about something like one of these?

Our leaders' skin was clean and spotless, 
like pure snow or white milk.
Their bodies were healthy,
pink like coral and brilliant like sapphires.

Our leaders were clean and spotless, 
like pure snow or white milk.
Their bodies were healthy,
pink like coral and strong like sapphires.

**Comment by TomWarren** [comment]
The UDB of LAM 4:7 now reads:
\v 7 Our leaders are like pure snow or white milk,
\q2  they were so clean and spotless.
\q1 Their bodies were healthy,
\q2 pink like coral and brilliant like sapphires.
\q1
\v 8 Our leaders faces are blacker than soot,
\q2 and no one recognizes them when they walk in the streets.
\q1 Their skin was shriveled and it hung on their bones,
\q2 and it became as dry as a stick of wood.

Thanks Susan, 

Tom

**Comment by SusanQuigley** [comment]
Thank you for changing it. Here's a little more.

\v 8 Our **leaders** faces are blacker than soot,
\q2 and no one recognizes them when they walk in the streets.
\q1 Their skin **was shriveled** and it **hung** on their bones,
\q2 and it **became** as dry as a stick of wood.

"leaders" should have an apostrophe at the end.

What would you think of changing the tense in the last two lines so that it matches the tense in the first two lines of v8?
\q1 Their skin **has** shriveled and it **hangs** on their bones,
\q2 and it **has become** as dry as a stick of wood.

**Comment by TomWarren** [comment]
Yep. 
The UDB of LAM 4:8 now reads:
\v 8 Our leade**rs' f**aces are blacker than soot,
\q2 and no one recognizes them when they walk in the streets.
\q1 Their skin **has shriveled** and it hangs on their bones,
\q2 and it **has become** as dry as a stick of wood.

Thanks Susan, 

Tom

**Comment by SusanQuigley** [comment]
Thank you, Tom.
