### ISSUE TITLE
2Ch 6:29 UDB extra space - Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#231]
2Ch 6:29 UDB and then if your Israelite people earnestly **plead ,** or if 

There is a space between "plead" and the comma.

**Comment by TomWarren** [comment]
The UDB of 2CH 6:29 now reads:
\v 29 and then if your Israelite people earnestly **plead, o**r if even just one person does so—if they stretch out their hands toward this temple and pray to you because they know the weakness and sorrow in their own hearts—

Thanks Susan, 

Tom
