### ISSUE TITLE
2ch 9:10-12 UDB  Missing info

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#234]
The UDB doesn't say anything about Solomon making steps and musical instruments with the algum wood.

**Comment by TomWarren** [comment]
The UDB of 2CH 9:10-12 now reads:
\v 10-12 King Solomon gave to the queen from Sheba everything that she wanted. He gave her more than she had given to him. Then she and those who came with her returned to her own land.
\p In the ships that belong to King Hiram, Hiram's workers and Solomon's workers brought gold from Ophir. They also brought a large amount of algum wood. The wood was used to make steps for the house of Yahweh, and they also used the wood to make harps and lyres for those who played music. No one had ever seen anything like the quality of those steps or the quality of those musical instruments in all the land of Judah.

Thanks Susan, 

Tom

**Comment by SusanQuigley** [comment]
Thanks, Tom.
\p In the ships that belong to King Hiram, 
Would you want "belong" to be past tense? Or without tense ("in King Hiram's ships")?

**Comment by TomWarren** [comment]
Checking the HEB, Hiram's ships were not mentioned in 10-12, just Hiram's men and Solomon's men. 
The UDB of 2CH 9:10-12 now reads:
\v 10-12 King Solomon gave to the queen from Sheba everything that she wanted. He gave her more than she had given to him. Then she and those who came with her returned to her own land.
\p The men of Hiram worked with the men of Solomon to bring gold from Ophir to the land of Judah. They also brought a large amount of algum wood. The wood was used to make steps for the house of Yahweh, and they also used the wood to make harps and lyres for those who played music. No one had ever seen anything like the quality of those steps or the quality of those musical instruments in all the land of Judah. 

Hope that helps, working on the right version, and all. 

Tom

**Comment by SusanQuigley** [comment]
Good change.

**Comment by TomWarren** [comment]
Added a bit of rewording, when I had a break ... 
 "No one in all the land of Judah had ever seen anything ...."

Thanks,
Tom

**Comment by SusanQuigley** [comment]
Thanks. That's clearer.
