### ISSUE TITLE
2ch 9:15, 16 UDB kg weight doesn't fit ULB shekel weight

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#236]
ULB King Solomon made two hundred large shields of beaten gold. **Six hundred shekels** of gold went into each one. 16He also made three hundred shields of beaten gold. **Three minas of gold** went into each shield;

UDB: King Solomon's workers took this gold and hammered it into thin sheets and covered two hundred large shields with those thin sheets of gold; they put about **3 and one-half kilograms** of gold on each shield. 16His workers made threw hundred smaller shields. They covered each of them with **one and three-quarters kilograms** of gold.

If 1 shekel = 11 grams, 600 shekels = 6,600 grams = 6.6 kilograms. (**six and one-half kilograms**)
If 1 mina = 550 grams, 3 minas - 1,650 grams = 1.65 kilograms (**one and three-quarters kilograms**)

Another possibility is to make the UDB weights the same as those in 1 Kings 10:16, 17: **six kilograms** and **1.7 kilograms**.

**Comment by TomWarren** [comment]
The UDB of 2CH0:15-16 now reads:
\v 15 King Solomon's workers took this gold and hammered it into thin sheets and covered two hundred large shields with those thin sheets of gold; they put about **six and one-half kilograms** of gold on each shield.
\v 16 His workers made three hundred smaller shields. They covered each of them with **one and three-quarters kilograms** of gold. Then the king put those shields in the Hall of the Forest of Lebanon.

For continuity, the ULB of 1KI 10:16-17 was changed to read:
\v 16 King Solomon's workers took this gold and hammered it into thin sheets and covered two hundred large shields with those thin sheets of gold. They put **six and one-half kilograms** of gold on each shield.
\v 17 His workers made three hundred smaller shields. They covered each of them with **one and three-quarters** kilograms of gold. Then the king put those shields in the Palace of the Forest of Lebanon.

Thanks,

Tom
