### ISSUE TITLE
2ch 9:18  "rounded top" or "gold footstool" 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#237]
2Ch 9:18 ULB **the top of the throne was round behind.** 

Hebrew, UDB, and other versions tell about a gold footstool attached to the throne or its steps -

**Comment by TomWarren** [comment]
Rework on ULB of 2CH 9:18, it now reads:
\v 18 There were six steps to the throne, and a footstool was attached to the throne. On both sides of the throne there were armrests,  and there was  a lion statue standing on each side.

The footstool was apparently attached to the throne, not to the steps.
The UDB of 2CH 9:18 now reads:
\v 18 There were six steps in front of the throne. There was a gold footstool that was attached to the throne. At each side of the throne there was an armrest, and alongside each armrest there was a statue of a lion. 

Hope that is more clear. 

Tom
