### ISSUE TITLE
2ch 9:28 UDB  Musri vs Egypt

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#239]
UDB: Solomon's agents brought horses from **the Musri area** and other places.
ULB: They brought horses for Solomon from **Egypt** and from all the lands.

Could "the Musri areas" in the UDB be changed to "Egypt"?

**Comment by TomWarren** [comment]
Yep. מִצְרַיִם is Mitzraim. Musri is following the CEV. 
The UDB of 2CH 9:28 now reads:
\v 28 Solomon's agents brought horses from Egypt and from many other lands to the land of Judah.
