### ISSUE TITLE
MAT 1:11-12

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/udb-en#24]
From Paul Fahnestock on the field:
In Matthew 1: 11-12 of the UDB, we have 2 grandfathers mentioned who were actually fathers.

Josiah was the  father of Jechoniah v 11

Shealtiel was the father of Zerubbabel v 12

@Wysackyprof The Note at verse 12 says that father is wrong and he was the grandfather. 
The Greek text says that “Shealtiel begat Zerubbabel.”

**Comment by TomWarren** [comment]
This is a complex issue that we visited carefully some months back. Father is often used for ancestor or other familial link (sometimes skipping many generations). I think the text is correct, given the other evidence. It is, I must say, mind-bogglingly complex, but I think we have it.

**Comment by TomWarren** [comment]
This is a complex problem. There are some good solutions supported by the LXX, that seem best fitted to the rest of the biblical account. I think this is one of the more difficult puzzles from the Hebrew text.But I think we have it right here.

**Comment by SusanQuigley** [comment]
Matthew 1:9-11 has this note.


  *
Josiah was the father of Jechoniah - Josiah was actually Jechoniah's grandfather.

It looks like it is saying that the ULB is wrong.  How about if I add a tW link to ”ancestor, father, forefather” and change the note to this.


  *
Josiah was the father of Jechoniah - In lists of ancestors and descendants,sometimes the word ”father” refers to a grandfather or some other ancestor. Josiah was actually Jechoniah's grandfather.



On Jun 23, 2016, at 10:50 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


This is a complex problem. There are some good solutions supported by the LXX, that seem best fitted to the rest of the biblical account. I think this is one of the more difficult puzzles from the Hebrew text.But I think we have it right here.

**Comment by pohlig** [comment]
I like Susan's suggestion. I was thinking myself that the note could be viewed as a little cryptic. It's better to specify that "father" can mean "grandfather" or "ancestor." There is some fluidity here.

**Comment by SusanQuigley** [comment]
OK. Done.
On Jun 23, 2016, at 11:16 AM, pohlig <notifications@github.com<mailto:notifications@github.com>> wrote:


I like Susan's suggestion. I was thinking myself that the note could be viewed as a little cryptic. It's better to specify that "father" can mean "grandfather" or "ancestor." There is some fluidity here.

**Comment by ChrisJarka** [comment]
Should the note for verse 12 also be edited?

**Comment by hmw3** [comment]
Looks to me like the tN has been adjusted.
