### ISSUE TITLE
2ch 10:2 Clarifying the order of events

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#241]
UDB 1All the people of northern Israel went to the city Shechem in order to appoint Rehoboam to be their king. So Rehoboam also went there. 2Jeroboam son of Nebat, fled to Egypt to escape from King Solomon.  But when he heard about the people wanting to appoint Rehoboam to be their king, he returned from Egypt to Israel.

It would be clearer that Jeroboam had fled to Egypt some time before Rehoboam went Shechem if the words "Now" and "had" were added to the first sentence of v2.

1All the people of northern Israel went to the city Shechem in order to appoint Rehoboam to be their king. So Rehoboam also went there. 2 **Now** Jeroboam son of Nebat, **had fled** to Egypt to escape from King Solomon.  But when he heard about the people wanting to appoint Rehoboam to be their king, he returned from Egypt to Israel.

**Comment by TomWarren** [comment]
The UDB of 2CH 10:2 now reads:
\v 2 Now Jeroboam son of Nebat had fled to Egypt to escape from King Solomon. While he was in Egypt he heard about the people wanting to appoint Rehoboam to be their king, and so he returned to Israel from Egypt.

Hope that is close. 
Thanks, 

Tom

**Comment by SusanQuigley** [comment]
Thanks. It's better than my suggestion.
