### ISSUE TITLE
2ch 10:10 UDB Typo - Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#242]
The young men who had grown up with him replied, "Those men have said that your father forced them to work very hard for **him ,**

There is a space between "him" and the comma.

**Comment by TomWarren** [comment]
Easy. 
The UDB of 2CH 10:10 now reads:
\v 10 The young men who had grown up with him replied, "Those men have said that your father forced them to work very hard for **him, so** they want you to reduce the work and taxes that your father required from them. But this is what you should tell them: 'My little finger is thicker than my father's waist.'
