### ISSUE TITLE
2Ch 10:11 UDB  Identity of speaker

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#243]
In the ULB and most versions, verse 11 is just a continuation of what Jeroboam's friends are telling him to tell the people. 

**ULB** So now, although my father burdened you with a heavy yoke, I will add to your yoke. My father punished you with whips, but I will punish you with scorpions.'"

The UDB follows the TFT and makes v 11 be Jeroboam's friends explaining to him how he should treat the people.
**UDB**: What we mean is that your father required the people to work hard and pay high taxes. But tell them that you will make those loads heavier. It was as though your father whipped them with leather whips, but you will whip you with scorpions."

I don't know if you are ok with that or if  you want the UDB to be like other versions.
If you do allow the UDB to stand as is, a minor change is needed. 
The final word "you" needs to be changed to  "them": 
but you will whip **them** with scorpions."

**Comment by TomWarren** [comment]
The UDB was edited to follow the ULB.
The UDB of 2CH 10:11 now reads:
\v 11 My father required you people to work hard and pay high taxes, but I will make those loads even heavier. My father whipped you with leather whips, but I will whip you with scorpions."

Hope that works. 
Thanks,

Tom
