### ISSUE TITLE
2CH 20:2 name mismatch

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#244]
UDB They have already come to Hazazon Tamar!" Another name for that place is Engedi

ULB See, they are in Hazazontamar," that is, Engedi.

Hazazon Tamar vs Hazazontamar

**Comment by TomWarren** [comment]
FYI, we are doing a "use the NIV for proper names" (for consistency, and to be more broadly in agreement with other ENG translations. Keep sending these in when you find them, but just wanted you to know that that project is going on at this time. We hope to finish in before the end of May. This rendering in the UDB was checked against the NIV, and it is a match. SO ULB and UDB and NIV are in agreement. (NET had "Harzezon Tamar" just to be contentious.) 
The ULB of 2CH 20:2 now reads:
\v 2 Then some came who told Jehoshaphat, saying, "A large multitude is coming against you from beyond the Dead Sea, from Edom. See, they are in Hazazon Tamar," that is, Engedi.

Thanks Kim, 

Tom
