### ISSUE TITLE
2Ch 26:12 UDB  Implied or extraneous?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#245]
UDB: There were leaders appointed to be in charge of the soldiers. **They came from the traditional families of Judah,** and were 2,600 in number.

ULB: The whole number of the heads of ancestral houses, fighting men, was 2,600.

I don't know if the UDB's "They came from the traditional families of Judah" is implied info or extraneous info. I'm not sure how it relates to the ULB's "the heads of ancestral houses"

**Comment by TomWarren** [comment]
The HEB גִּבּוֹר is translated "mighty men" some use "valiant men" or others (the UDB below, strongest soldiers). 
 
The ULB of 2CH 26:12 now reads:
\v 12 The whole number of the heads of ancestral houses who led the mighty men was 2,600.

The UDB of 2CH 26:12 now reads:
\v 12 The total number of the family leaders who led the strongest soldiers in battle was 2,600 in number.

Thanks Susan, 

Tom
