### ISSUE TITLE
2Ch 26:5-27:2 Amaziah vs Uzziah

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#246]
UDB: (King) Amaziah   (26:1-3 has Uzziah and his father Amaziah.)
ULB: (King) Uzziah

It looks like the most of the occurrences of "Amaziah" in 26:5-27:2 of the UDB need to be changed to Uzziah.

**Comment by TomWarren** [comment]
The UDB of 2CHO 27:2 now reads:
\v 2 Jotham obeyed Yahweh and did what Yahweh approved. He followed the example of his father Uzziah in everything he did. (He did not, however, go into the Temple of Yahweh to burn incense as his father had done.) Yet the people of Judah continued to do the things that showed how sinful they had become. 

Thanks Susan, 
Tom

**Comment by TomWarren** [comment]
Thanks for getting me focused ... 
I was dealing with other matters above, hope this doesn't complicate a complicated section. 

Amaziah to Uzziah
UDB of 2CH 26:6, 8, 9, 10, 11, 14, 16, 18, 19, 21, 22, 23, and 2CH 27:2 Amaziah was changed to Uzziah.

Tom
