### ISSUE TITLE
2Ch 26:19 UDB "there"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#248]
He became very angry with the priests, but suddenly **there** spots of leprosy appeared on his forehead.

I'm not sure if "there" is intentional or a left over from an earlier revision.

**Comment by TomWarren** [comment]
The UDB of 2CH 26:19 was reworded to read:
\v 19 Now Amaziah was holding in his hand a pan for burning incense, and he became very angry with the priests. While he was expressing his anger, while he stood beside the altar of incense in front of the priests, suddenly spots of leprosy appeared on his forehead.

Hope that is more understandable. 
Tom

**Comment by SusanQuigley** [comment]
That's clearer. Thanks.
