### ISSUE TITLE
2CH 33:18 typo

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#249]
The other things that happened while Manasseh was ruling, including his prayer to God and the messages from Yahweh that the prophets spoke to him, are written in the book of the kings ofIsrael. 

Space needed before Israel.

**Comment by TomWarren** [comment]
Yep.
The UDB of 2CH 33:18 now reads:
\v 18 The other things that happened while Manasseh was ruling, including his prayer to God and the messages from Yahweh that the prophets spoke to him, are written in the book of the **kings of Israel.**

Thanks Kim, 

Tom
