### ISSUE TITLE
2ch 30:23 UDB Stray period

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#250]
Then the whole group decided to celebrate for seven more days, so they did: they celebrated joyfully **for seven .more days**. 

There's a period between "seven" and "more"

**Comment by TomWarren** [comment]
The UDB of 2CH 30:23 now reads:
\v 23 Then the whole group decided to celebrate for seven more days; so they celebrated joyfully for seven more days.

A bit repetitive, but that was the way the source read. 
Greetings, 

Tom
