### ISSUE TITLE
GEN 14:10 typo

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#252]
TheValley of Siddim was full of tar pits.

space needed above

**Comment by TomWarren** [comment]
This was fixed when the cap was removed. 
The ULB of GEN 14:10 now reads:
\v 10 Now **the Valley of Siddim** was full of tar pits, and as the kings of Sodom and Gomorrah fled, they fell in there. Those who were left fled to the mountains.

The USFM seems to lag behind the GitHub.

Thank you, Kim, 

Tom
