### ISSUE TITLE
Acts 2:46 UDB What kind of meal was this?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#253]
Every day they continued meeting together in the temple area. **They would have a meal together going from house to house,** and when they did, they were happy and shared what they had together. 

This sounds like they traveled to different houses for the one meal. Hors D'oeuvres at the first house, salad at the next, main course at the next, dessert at the last. (I wish I could remember what we call that kind of meal.)

They would go to one another's houses to have meals together
They would invite one another to their homes to have meals together

**Comment by TomWarren** [comment]
You are thinking of a "Progressive Dinner." Right?

The UDB of ACT 2:46 now reads:
\v 46 Every day they gathered together in the temple area, and then they would have meals together in their homes. They were happy when they were eating together, and they shared what they had with one another.

Thanks Susan, 

Tom

**Comment by SusanQuigley** [comment]
That's it. Thanks.

**Comment by TomWarren** [comment]
A lot of "togethers" in there.

**Comment by SusanQuigley** [comment]
It certainly makes the point.
