### ISSUE TITLE
1ti 2:11 UDB translation of "submission"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#254]
ULB A woman should learn in silence and with all submission.
UDB: When men are teaching the believers, women should listen in silence **and not ask questions about what they hear**.

The UDB seems  to have translated "submission" as if 1 Corinthians 14:34-35 were its definition. But this is a different book. Could it be something a little more general?

When men are teaching the believers, women should listen in silence **and humility**.
When men are teaching the believers, women should listen in silence **and submit to what is taught**.
When men are teaching the believers, women should listen in silence **and be ready to obey God's word**.
When men are teaching the believers, women should listen in silence, **and not challenge what the men are teaching.**

**Comment by TomWarren** [comment]
The UDB of 1TI 2:11 now reads:
\v 11 When men are teaching the believers, women should listen quietly, and they should give respect to their teachers and do all they can to learn from them.

Thanks Susan, 

Tom
