### ISSUE TITLE
3jn 1:11 UDB Any one

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#255]
3jn 1:11 UDB **Any one** who keeps doing what is bad has never seen God.

Anyone

(There are 8 instances of "any one of" in the UDB. They are fine.)

**Comment by TomWarren** [comment]
The UDB of 3JN 1:11 now reads:
\v 11 Dear friend, do not imitate a bad example like that. Instead, keep imitating good examples. Remember that people who do good deeds truly belong to God. **Anyone** who keeps doing what is bad has never seen God.

Thanks Susan, 

Tom
