### ISSUE TITLE
Rom 3:1 UDB  Missing info

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#257]
ULB: Then what advantage does the Jew have? And what is the benefit of circumcision? 

UDB: If being circumcised does not cause God to accept Jews there is no advantage in being a Jew over being a non-Jew. Being circumcised does not benefit us Jews at all! 

The UDB makes it sound like Paul is saying that there is no advantage in being a Jew. But he was only bringing up what some people might be thinking.

Could it be re-TFTd?
**Someone may object to this, saying,** "If being circumcised does not cause God to accept Jews there is no advantage in being a Jew over being a non-Jew. Being circumcised does not benefit us Jews at all!"
or 
**Someone might say then,** "If being circumcised does not cause God to accept Jews there is no advantage in being a Jew over being a non-Jew. Being circumcised does not benefit us Jews at all!"
or 
**Someone might say then, "If that is true, then it appears that there is no advantage to be a Jew over a non-Jew, and being circumcised does not benefit us Jews at all."

**Comment by TomWarren** [comment]
The UDB of ROM 3:1 now reads, following your 3rd suggestion:
\v 1 Someone might say then, "If that is true, then it appears that there is no advantage to be a Jew over a non-Jew, and being circumcised does not benefit us Jews at all."

Thanks Susan, 

Tom

**Comment by SusanQuigley** [comment]
Thanks for changing it.
Sorry I wrote too fast. It would be good to change "be" to "being" and to add a "being."
"If that is true, then it appears that there is no advantage to **being** a Jew over **being** a non-Jew, and being circumcised does not benefit us Jews at all."

**Comment by TomWarren** [comment]
Another that I also caught. It is difficult to edit using GitHub.
The UDB of ROM 3:1 reads:
\v 1 If being circumcised does not cause God to accept Jews there is no advantage in being a Jew over being a non-Jew. Being circumcised does not benefit us Jews at all!

I think that's it.

Thanks,

Tom
