### ISSUE TITLE
Rom 3:2 UDB Conjunction needed

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#258]
UDB: Being Jews has many benefits. First of all because it was to their ancestors that God spoke his words, words that show us who he is.

The beginning of v2 needs something to show that Paul is answering the objection/question brought up in v1. 

**But** being Jews has many benefits. First of all because it was to their ancestors that God spoke his words, words that show us who he is.
or 
**But I tell you that** being Jews has many benefits. First of all because it was to their ancestors that God spoke his words, words that show us who he is.

**Comment by TomWarren** [comment]
Yep.
The UDB of ROM 3:2 now reads:
\v 2 But I tell you that being Jews has many benefits. First of all because it was to their ancestors that God spoke his words, words that show us who he is.

Thanks Susan, 

Tom
