### ISSUE TITLE
Rom 3:4 UDB Typo

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#260]
I No, it certainly does not mean that! 

The "I" needs to be deleted

**Comment by TomWarren** [comment]
The UDB of ROM 3:4 now reads:
\v 4 No, it certainly does not mean that! God always does what he has promised, even though people do not. All those who accuse God of not keeping his promises to us Jews are very mistaken. King David wrote about this:

Thanks, 

Tom
