### ISSUE TITLE
Rom 11:26 UDB whole Israel

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#261]
And then God will save **whole Israel**. 

The phrase "whole Israel" sounds odd.

**Comment by TomWarren** [comment]
The UDB of ROM 11:26 now reads:
\v 26 And then God will save **all of Israel.** Then these words in the scriptures will become true:
\p "The one who sets his people free will come from where God is among the Jews. He will forgive the sins of the Israelite people."

Thanks Susan, 

Tom
