### ISSUE TITLE
REV 2:1 UDB the one who..., and the one who

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#29]
Rev 2:1 UDB The one who holds the seven stars in his right hand, and the one who walks among the seven golden lampstands says this:,
This sounds like two people. Could it be changed to this?
The one who holds the seven stars in his right hand and walks among the seven golden lampstands says this:,

Also the comma is not needed after the colon.

**Comment by TomWarren** [comment]
This has been fixed. Thanks for the good catch.
