### ISSUE TITLE
NUM 33:3

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#3]
Num 33:3 UDB
the day after we celebrated the Passover, 
The first person seems odd here. Everything else is third person.

**Comment by TomWarren** [comment]
It is third person,מִֽמָּחֳרַ֣ת הַפֶּ֗סַח יָצְא֤וּ and should be "from the next day after the Passover they went out." The UDB often changes the person (here third to first), and these should be changed to match the ULB. There are many of these in the Prophets and Lamentations. 
UDB: **\v 3 On the fifteenth day of the first month of the year, the day after they celebrated the Passover, they left the city of Rameses in Egypt and marched boldly while the Egyptian army was coming behind them.**
