### ISSUE TITLE
REV 2:3 UDB because of you believe

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#31]
I know also that you endure patiently when you suffered because of you believe in me and continue to serve me steadfastly. 

**because of you believe** - Please delete "of"
"Endure" and "continue" are present tense. Should "suffered" also be present tense?

This could easily be interpreted as "I know ... because you believe in me and continue..."

How about one of these?
I know also that you endure patiently when you suffer because you believe in me and **that you** continue to serve me steadfastly. 
OR
I know also that you endure patiently when you suffer **for believing** in me and **that you** continue to serve me steadfastly.

**Comment by pohlig** [comment]
Fixed it.
