### ISSUE TITLE
REV 2:16 UDB  the word of God that comes out of my mouth

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#32]
ULB:  the sword of my mouth. 
UDB:  the word of God that comes out of my mouth

I like the UDB because it is easy to understand, but it seems to be treating "the sword of my mouth" as an ordinary metaphor that can be "defigured."  I was thinking that it was a symbol -- something that should be kept in the translation.

The UDB keeps the image in 1:16 where it first appears: A sword with two sharp edges was coming out of his mouth.

Would it be good to keep the image of the sword in the UDB in 2:16? Or would it be good for me to add a note for "sword of my mouth" explaining that Jesus spoke of God's word as if it were a sword and then link it to the page for Metaphor?

**Comment by TomWarren** [comment]
Others may chime in, but if the ULB is to be as close to the Greek as the English can carry, the way it is seems correct. If there is a barrier for the MTT with the ULB, a Translation Note would be helpful, but expansive alternations may be best in the UDB. 
There you go.

**Comment by SusanQuigley** [comment]
I was wondering if "sword" here is a symbol  that should be kept in 2:16 of the UDB. That is, instead of saying "The word of God that comes out of my mouth," should it say something like "The sword that sticks out from my mouth"?

**Comment by pohlig** [comment]
I think that 1:16 should be left the way it is in both versions. For 2:16 UDB, I think that the best thing is to retain the symbol of sword, but to add the explanation, in this way:
"I will make war against them with the sword in my mouth, the word of God." As a rule, I don't support explaining symbols in apocalyptic literature, but I think it's helpful here. In this way, the UDB gives a possible model to MTTs who will wonder what to do about this symbol.

**Comment by TomWarren** [comment]
Most visualizations of this (for what that is worth) see the sword coming out of Christ's mouth to attack the enemies of Christ as he leads his angels and his valiant ones in battle. 
Sword of my mouth, can be the sword which is the same as my mouth (epexegetic use) or the sword that comes out of my mouth. Either is interpretative.I don't remember reading the option you suggestion, "the sword that sticks (is stickiing?) out of my mouth. Whatever it is, it is at least an apocalyptic metaphor, and that apocalyptic imagery should be interpreted apocalyptically.

**Comment by SusanQuigley** [comment]
Funny, I always pictured a sword protruding from his mouth with which he would attack his enemies-- and I understood "comes out of" in that sense. I guess it really doesn't matter. Hopefully translators will be able to use something really generic like "of" which only indicates that there is some relationship between the sword and the mouth without specifying exactly what it it. And hopefully readers will recognize it as a weapon that Jesus will use, and people who study the book will recognize it as the Word of God. Thanks for showing me the specific image I had not seen before.

**Comment by pohlig** [comment]
You're welocme.
