### ISSUE TITLE
MRK 9:19 typo?

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#33]
19Jesus replied by saying to those people, "You faithless people! How long must I put up with you! Bring the boy to me!"

How long must I put up with you! --Should this exclamation mark be a question mark?

**Comment by TomWarren** [comment]
The overuse of the exclamation point and underuse of the question mark. 
This had been tended-to.
Thanks.

**Comment by pjoakes** [comment]
It seems to me that this is a rhetorical question and should be made into a statement in the UDB.

Perry Oakes, Ph.D.
Chief Language Officer
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>

[cid:image002.png@01D116FB.66313BC0]

On Jun 28, 2016, at 2:49 PM, kim-putter <notifications@github.com<mailto:notifications@github.com>> wrote:


19Jesus replied by saying to those people, "You faithless people! How long must I put up with you! Bring the boy to me!"

How long must I put up with you! --Should this exclamation mark be a question mark?

**Comment by TomWarren** [comment]
Rhetorical question replaced with statement. 

\v 19 Jesus replied by saying to those people, "You faithless people! You test my patience! Bring the boy to me."
