### ISSUE TITLE
MRK 9:50 missing phrase

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#35]
Salt is useful to put on food, but you cannot make it taste salty again if it becomes flavorless. Do good to each other, like salt adds flavor to food."

In this verse, the final phrase about "being at peace with one another" seems lost.

**Comment by TomWarren** [comment]
Yes. Here is the repair:

\v 50 Salt is useful to put on food, but you cannot make it taste salty again if it becomes flavorless. Do good to each other, like salt adds flavor to food. And live in peace with one another."
