### ISSUE TITLE
Rev 10:6 UDB no longer delay

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#37]
UDB: The angel said that he would surely no longer delay what God had planned to do.

This seems to imply that the angel had authority or power to delay what God planned to do. 
Most versions are like the ULB and just say that there will be no more delay or waiting. 
The NLT says that "God won't wait any longer."
If the ULB is to indicate who has been delaying things, could it be changed to God?

**Comment by pohlig** [comment]
Changed UDB 10:6 to:
...That God would no longer delay in doing what he had planned to do.

**Comment by SusanQuigley** [comment]
Thank you, Jim.

**Comment by TomWarren** [comment]
The angel swore by God, ... and said ... carefully following the Gk. I think this is still ok. 

\s5
\v 5 Then the angel I saw standing on the sea and the earth, raised his right hand to heaven
\v 6 and swore by him who lives forever and ever, who created heaven and all that is in it, the earth and all that is on it, and the sea and all that is in it, and the angel said, "There will be no more delay.
\v 7 But on the day when the seventh angel is about to sound his trumpet, then the mystery of God will be accomplished, just as he proclaimed to his servants the prophets."
