### ISSUE TITLE
Rev 11:18  Who are the servants? Who will God reward?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#39]
UDB: All the people listed in the rest of that sentence are the servants:  the prophets and the rest of God's people who honor him.
ULB: Only the prophets are the servants.

Another way of looking at the difference between ULB and UDB is to look at the groups God will bless.
UDB God will reward all the servants, which consists of **two groups**: the prophets and the rest of the  people who honor God  
ULB: God will reward **three groups** of people: the prophet-servants, the believers, and those who feared God's name.

**Comment by TomWarren** [comment]
UDB Rev 11:18 now reads:
\v 18 The unbelieving people of the nations were angrily raging at you. 
\q1 As a result you have become very angry with them.
\q1 You have decided that this is the right time for you to judge all those who have died.
\q1 The time has come for you to reward **all your servants who were the prophets** and **the others who believe in you,** 
\q1 and **all those who honor you,**
\q1 and this includes those who are small and those who are great.
\q1 It is time for you to destroy the people who destroy the earth."

ULB Rev 11:18 now reads:
\s5
\q
\v 18 The nations were enraged, 
\q2 but your wrath has come.
\q2 The time has come for the dead to be judged
\q and for you to reward your servants the prophets, 
\q2 those who are believers, and those who feared your name, 
\q2 both the unimportant and the mighty.
\q And the time has come for you to destroy those who are destroying the earth."

**Comment by hmw3** [comment]
Is this ready to be closed?

**Comment by SusanQuigley** [comment]
Tom's fix looks good to me.
