### ISSUE TITLE
REV 9:11 UDB the underworld

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#41]
UDB 9:11, 11:7, 17:8  These all follow the TFT and have "the underworld" for "abyss".
I don't see any other versions that use this word.

UDB 9:1 has "the shaft that went down but had no ending."

**Comment by TomWarren** [comment]
UDB Rev 0:11 now reads:
\v 11 The king who ruled over them was the angel of the shaft that went down but had no ending. His name in the Hebrew language is Abaddon. In the Greek language it is Apollyon. Both of these names mean "Destroyer."

UDB Rev 11:7 now reads: 
\v 7 When they have finished announcing to people the message from God, the beast that comes up from the shaft that went down but had no ending, will attack them, overcome them, and kill them. 

UDB Rev 17:8 now reads: 
\v 8 The beast that you saw lived previously. Eventually God will destroy him, but now he is dead. He is about to come up from the shaft that went down but had no ending. When that beast appears again, the people on the earth will be amazed. They are people whose names have not been written in the Book of Life before God created the world.

**Comment by pjoakes** [comment]
It looks like there is an extraneous comma in UDB Rev 11:7 after “no ending”

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Jul 11, 2016, at 1:40 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


UDB Rev 0:11 now reads:
\v 11 The king who ruled over them was the angel of the shaft that went down but had no ending. His name in the Hebrew language is Abaddon. In the Greek language it is Apollyon. Both of these names mean "Destroyer."

UDB Rev 11:7 now reads:
\v 7 When they have finished announcing to people the message from God, the beast that comes up from the shaft that went down but had no ending, will attack them, overcome them, and kill them.

UDB Rev 17:8 now reads:
\v 8 The beast that you saw lived previously. Eventually God will destroy him, but now he is dead. He is about to come up from the shaft that went down but had no ending. When that beast appears again, the people on the earth will be amazed. They are people whose names have not been written in the Book of Life before God created the world.

**Comment by TomWarren** [comment]
UDB Rev 17:8 now reads:
\v 8 The beast that you saw lived previously. Eventually God will destroy him, **but now he is not alive.** He is about to come up from the shaft that went down but had no ending. When that beast appears again, the people on the earth will be amazed. They are people whose names have not been written in the Book of Life before God created the world.

**Comment by TomWarren** [comment]
The comma was removed: 
UDB Rev 11:7 now reads:
\v 7 When they have finished announcing to people the message from God, the beast that comes up from the shaft that went down but had no ending will attack them, overcome them, and kill them.
