### ISSUE TITLE
Rev 14: 4 UDB  chaste

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#42]
I don't expect  many MTTs to know the word "chaste."

**Comment by TomWarren** [comment]
"Virgin" seems odd referring to a man (but that is the phrasing. And trying to keep the male/female distinction clear. Went with:

\v 4 Those 144,000 are those who did not corrupt themselves with women; **for they never had sexual relations.** They are the ones who follow the lamb wherever he goes. These are the ones whom the lamb had redeemed for God from among the people of earth; they are the ones whom the lamb had first offered to God and to himself.

**Comment by SusanQuigley** [comment]
Good morning. Tom.  Thanks for coming up with a change. But it's not showing up on Door43. I checked Github, and it's not there yet.

**Comment by TomWarren** [comment]
I may have done all but sync.  Try it now.

**Comment by SusanQuigley** [comment]
It shows up now. Thank you.
