### ISSUE TITLE
Rev 15:1  UDB 2nd sentence

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#45]
UDB: God is so angry with rebellious people that this is the last time that he will punish them with the purpose of giving them an opportunity to turn away from their sinful behavior.

This  follows the TFT. It seems to be a lot for "which are the final plagues (for with them the wrath of God is completed."  Does "plague" really mean that the punishment is intended to lead to repentance?  If it does, I'll add a note that explains plague.

If plague does not mean that, would something like any of these be adequate? 
This is the last time that God will punish people this way, for it will show all of his anger. 
This is the last time that God will punish people this way, for it will fully show how angry he is.
This is the last time that God will punish people this way, for after that, he will no longer be angry.
When they have punished the people these seven ways, God will no longer be angry, and they will not punish people any more.

**Comment by hmw3** [comment]
Went with this:
This is the last time that God will punish people this way, for it will fully show how angry he is.
