### ISSUE TITLE
Rev 4:7-8 Almighty

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#46]
The UDB uses "almighty" 8 times in Revelation. The ULB only uses it once.
UDB almighty: Rev 4:7-8, 11:16, 15:3, 16:7, 16:14, 19:6, 19:15, 21:22
ULB almighty: Rev 1:8

If the word "almighty" is to be used, it  would be easier if it were in the ULB instead. That way we could have a link to the tW page "almighty" and perhaps a note. But if it  is only in the UDB, there will be no tW page link to help MTTs understand it.

**Comment by hmw3** [comment]
Moved "Almighty" to ULB so can match tW list and UDB rendering to UDB. Accidentally called UDB commit Gen instead of Rev.

**Comment by SusanQuigley** [comment]
Rev 16:14 ULB does not have "Almighty." Is that intentional?

**Comment by hmw3** [comment]
No. It's now fixed.
