### ISSUE TITLE
Rev 15:5 UDB bowls?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#47]
UDB 15:5 The seven angels who had the bowls containing the seven different kinds of punishment
ULB 15:5 the seven angels with the seven plagues

The UDB has seven bowls in 15:5. But the angels are not given bowls until 15:7. Are there two different sets of bowls?

**Comment by hmw3** [comment]
Copied "whose duty it was to punish rebellious people in seven different ways" from v. 1.
