### ISSUE TITLE
Missing word in Romans 9:8?

### ISSUE THREAD

**Issue by jag3773** [Door43/udb-en#5]
_From @sewhite on March 11, 2016 14:56_

It says "What I mean is, not all of Abraham's descendants are the people that God as his own children." This is not grammatical. 

Should it be
"What I mean is, not all of Abraham's descendants are the people that God **considers** as his own children."

_Copied from original issue: unfoldingWord/udb-en#2_

**Comment by pohlig** [comment]
The verse had already been reworked to, "That is, the children of the flesh are not the children of God. But the children of the promise are regarded as descendants."
