### ISSUE TITLE
Rev 14:9-10 UDB missing symbolism of wine and cup

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#50]
Rev 14:9-10 The UDB does not have the symbolism of drinking the undiluted wine of God's wrath from the cup of God's wrath. Apparently it treats these images as metaphors instead of as symbols.

**Comment by TomWarren** [comment]
The UDB has:
he "will punish them very severely" which is rendering the image of "drinking the wine of God's wrath," albeit in a less memorable form.  
Do you have a suggested alternative for the UDB?

**Comment by SusanQuigley** [comment]
Current UDB:God will be angry with them and his anger will be like * wine that he will make them drink. 
Current ULB: he also will drink the wine of God's wrath, the wine that has been prepared and  poured unmixed into the cup of his anger. 

UDB: In order to include the idea of unmixed wine, who about adding the word "strong" where I put the asterisk.

**Comment by TomWarren** [comment]
The change had been made: 
\s5
\v 9 Another angel, a third one, came afterward, saying in a loud voice, "If people worship the beast and its image or allow its mark to be put on their foreheads or on their hands,
\v 10 God will be angry with them and his anger will be like strong wine that he will make them drink. He will torment them in burning sulfur in the presence of his holy angels and in the presence of the Lamb.
