### ISSUE TITLE
Rev 7:15  UDB waters...represent

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#52]
17:15 UDB  The waters that you saw in the city represents
Since "waters" is plural, "represent" would probably be better than "represents."

**Comment by TomWarren** [comment]
The UDB of Rev 7:15 now reads:
\v 15 Then the angel said to me, "The waters that you saw in the city represent many different kinds of people, and many different groups of people, and different languages that the people speak, where the prostitute sits.
