### ISSUE TITLE
EPH 3:18

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/udb-en#53]
In verse 18 is "how wide and long and high and deep is the love Christ."
I think that it might should be: "how wide and long and high and deep is the love **of** Christ."

**Comment by hmw3** [comment]
Picky, picky. I'll fix it, since I should have caught it.

________________________________

**Comment by TomWarren** [comment]
The UDB of Eph 3:18 now reads:
\v 18 so that you may be fully able to understand, along with the all those set apart for God, how wide and long and high and deep is the love of Christ.
