### ISSUE TITLE
MRK 4:35-39

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/udb-en#55]
Please see that the words "sea" and "lake" are interchanged on this passage. Is that correct?

On that same day, when the sun was setting, Jesus said to his disciples, "Let us cross over to the other side of the **_sea_**." 36 Jesus was already in the boat, so they left the crowd and sailed into the **_sea_**. Other people also went with them in other boats. 37 A strong wind came up and the waves started coming into the boat! The boat was soon nearly full of water!

38 Jesus was in the back part of the boat. He was sleeping with his head on a cushion. So they woke him up and said to him, "Teacher! Are you not concerned that we are about to perish?" 39 So Jesus got up and rebuked the wind. Then he said to the **_lake_**, "Be quiet! Be still! " The wind stopped blowing and then the **_lake_** became very calm.

**Comment by TomWarren** [comment]
The UDB of MRK 4:35-39 now reads:

Some of the words, "sea" and "lake" were supplied and were not in the original. And this rendering is a bit simpler and closer to the ULB in meaning. 

\s5
\p
\v 35 On that same day, when the sun was setting, Jesus said to his disciples, "Let us cross over to the other side."
\v 36 Jesus was already in the boat, so they left the crowd and sailed away. Other people also went along with them in their boats.
\v 37 A strong wind came up and the waves started coming into the boat! The boat was soon nearly full of water!

\s5
\v 38 Jesus was in the back part of the boat. He was sleeping with his head on a cushion. So they woke him up and said to him, "Teacher! Are you not concerned that we are about to die?"
\v 39 So Jesus got up and rebuked the wind and he spoke to the sea, "Be quiet! Be still!" The wind stopped blowing and then the sea became very calm.
