### ISSUE TITLE
Errors found doing chapter and verse number checks

### ISSUE THREAD

**Issue by phillip-hopper** [Door43/udb-en#6]
- [x] Verse not found, Mark 9:44
- [x] Invalid verse number, Zechariah 4:15
- [x] Invalid verse number, Zechariah 4:16
- [x] Verse out-of-order, Genesis 35:22
- [x] Duplicate verse , Genesis 35:22
- [x] Verse not found, Proverbs 25:24
- [x] Verse not found, Proverbs 26:19
- [x] Verse not found, 2 Timothy 1:4
- [x] Verse not found, Luke 20:38
- [x] Verse not found, Matthew 18:11

**Comment by hharrissWA** [comment]
Mark 9:44 is a textual variant that has a footnote explaining why it does not appear.

**Comment by phillip-hopper** [comment]
@hharrissWA: I think the same will be true for the verses in Zechariah 4. For those cases we can update the versification file used for doing the checks.

**Comment by phillip-hopper** [comment]
@hharrissWA: After more checking, it looks like the textual variant noted in the text is 9:46 rather than 9:44. To me it looks like verse 44 is just missing.

**Comment by pohlig** [comment]
Phil, 
Both vss. 44 and 46 are omitted, as not occurring in the best mss. This is so noted in the footnotes.
How do you update versification files to be used for checking?
Thanks.

**Comment by pohlig** [comment]
Zechariah 4: Many commentators support placing Zech 4:6b-10a after v. 14. This is what we have done also. The renumbering is reflected in the verse numberings in the UDB, where the original verse numbers are given in parentheses. I guess, to be fair, that the ULB vs. numbers should be treated in the same way.

**Comment by pohlig** [comment]
The text team wanted to put the verses in Zech. 4 back into the Hebrew text ordering, so they did so.

**Comment by pohlig** [comment]
Genesis 25:22 was carrying over into the next chunk in ULB. The UDB version began a new paragraph in this verse. I have altered the ULB version to imitate the UDB, and I have written a translation note to point out that a new paragraph begins near the end of this verse and carries over into the following verses.

**Comment by pohlig** [comment]
I think I fixed Prov. 25:24 in UDB. The sfm in the UDB was missing a slash mark.
I fixed the problem in 2 Tim. 1:4; there was no slash mark in the sfm.
I fixed the problem in Luke 20:38 UDB. There was no verse marker for v. 38.
Our versions purposely omit Matt. 18:11, as not being found in the best. mss. There is a footnote to that effect in the ULB.

**Comment by ChrisJarka** [comment]
Jim - please check that verse 22 is (sorta) repeated after verse 25. @pohlig

**Comment by lrsallee** [comment]
Deleted duplicate v22 in Gen 35 UDB.

**Comment by lrsallee** [comment]
Added empty missing Mrk 9:44 UDB with textual variant footnote from ULB.

**Comment by lrsallee** [comment]
Pro 26:19 UDB creates a verse bridge for 18-19 but the -19 was missing. I restored it.

**Comment by lrsallee** [comment]
Added empty Mat 18:11 verse to UDB with textual variant footnote from ULB.

**Comment by pohlig** [comment]
Larry wrote: "Added empty missing Mrk 9:44 UDB with textual variant footnote from ULB." We need the same thing for v. 46.

**Comment by lrsallee** [comment]
I see v 46 already has the note.

**Comment by lrsallee** [comment]
I find this part of the footnote on Mrk 9:44 confusing:

"from verses 44 and 46, vs. 44"

**Comment by pohlig** [comment]
I fixed it, removing "vs. 44." I also UDB-ed the textual variant "where their worm etc." for the UDB.
