### ISSUE TITLE
HEB 7:7 UDB

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/udb-en#61]
The translator thinks that there should be the word "than" before Abraham.
Instead
priests descended from him acknowledged that Melchizedek was greater Abraham. 
it should be
priests descended from him acknowledged that Melchizedek was greater **_than_** Abraham.

**Comment by pohlig** [comment]
Yes. I'll insert "than."

**Comment by pohlig** [comment]
"than" was already there. You must be looking at an old version?
