### ISSUE TITLE
MRK 14:31 major typo

### ISSUE THREAD

**Issue by kim-putter** [Door43/udb-en#63]
But Peter replied strongly, "Even if they kill me, I will say that I do not know you...

It's heresy I tell you!
...
"I will say" needs to be negated: "I will not say..."

**Comment by hmw3** [comment]
The heresy has been dealt with.
\v 31 But Peter replied strongly, "Even if they kill me, I will not say that I do not know you." And all the other disciples said the same thing.

For a moment I thought I had introduced a double negative, but I did a quick and dirty translation into Spanish, a "I didn't never do nothing to no one" language, and it's clear.
