### ISSUE TITLE
1CO 15:47-49

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/udb-en#66]
A facilitator noticed wording inconsistency in these three verses.
47The first man, Adam, belonged to the earth, for he was **_made of the_** dust. But the second man, Christ, belongs to heaven. 48All those who are **_made from the_** dust are just like Adam, the one who was **_made from the_** dust. All those who belong to heaven are just like Christ, the man from heaven. 49Just as God made us like the man who was **_made from_** dust, ...

And **_suggests_** this editing for consistency:
The wording “made of/from the dust” appears 3 times. In verse 49, the wording is simply “from dust”.  I suggest to synchronize the wording in all verses, so
- in verse 49, either add the word “the” in front of the word “dust”, or
- delete the word “the” every time it occurs before “dust” in verses 47 (once) and 48 (twice).

**Comment by TomWarren** [comment]
The UDB 1CO 15:47-49 now reads: 
UDB 1 
\s5
\v 47 The first man, Adam, belonged to the earth, for he was made from dust. But the second man, Christ, belongs to heaven. 
\v 48 All those who are made from dust are just like Adam, the one who was made from dust. All those who belong to heaven are just like Christ, the man from heaven.
\v 49 Just as God made us like the man who was made from dust, so he will also make us be like the man from heaven.
