### ISSUE TITLE
TIT 1:13

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/udb-en#69]
It seems that there is an extra verb (be) in this verse:
13 What he said is true, so correct them forcefully so that they **_may be believe_** and teach correct things about God.

Perhaps it should read:
13 What he said is true, so correct them forcefully so that they **_may believe_** and teach correct things about God.

**Comment by TomWarren** [comment]
The UDB of TIT 1:13 now reads:
\v 13 What he said is true, so correct them forcefully so that they may believe and teach correct things about God.
