### ISSUE TITLE
2CO 10:4-6

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/udb-en#71]
The RU translator found this passage in the UDB not adequate.

Here is what the translator stated:
_...feel strongly that some important meaning is missing from the UDB translation. These verses in English talk about demolishing strong holds and taking our thoughts captive. The UDB leaves all of this out._ 

Here is what Rodney White, MAST facilitator, stated:
_I agree with the translators concerning 2 Cor. 10:4-6.  I believe that the UDB has missed the central idea of the passage.  The UDB has translated the passage as though it were saying that our struggle is against unbelievers, that we are to change their thoughts.  The idea in the Greek is that the battle ground is our own mind.  We are taking our own thoughts captive.  I suggest that someone reexamine this passage._

**Comment by TomWarren** [comment]
The UDB of 2CO 10:4-6 now reads: 
\s5
\v 3 For though we now are living in our physical bodies, we are fighting like armies fight.
\v 4 And we are fighting with weapons, but these weapons are not designed by human beings, but by God. These weapons are powerful, so powerful that they can tear apart any false arguments.

\s5
\v 5 In this way we can tear apart every false argument and all those who rise up against God. Those are the ones who try to keep people from knowing him. We keep and hold every thought that people have and we take those thoughts as our prisoners. God would work in those who did not obey him, and they will him turn to him, and one day they will obey Christ.
\v 6 When you completely obey Christ yourselves, we will be ready to punish any who remain disobedient to him.

**Comment by pjoakes** [comment]
Stray “him” below:

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Aug 3, 2016, at 11:34 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


The UDB of 2CO 10:4-6 now reads:
\s5
\v 3 For though we now are living in our physical bodies, we are fighting like armies fight.
\v 4 And we are fighting with weapons, but these weapons are not designed by human beings, but by God. These weapons are powerful, so powerful that they can tear apart any false arguments.

\s5
\v 5 In this way we can tear apart every false argument and all those who rise up against God. Those are the ones who try to keep people from knowing him. We keep and hold every thought that people have and we take those thoughts as our prisoners. God would work in those who did not obey him, and they will him turn to him, and one day they will obey Christ.
\v 6 When you completely obey Christ yourselves, we will be ready to punish any who remain disobedient to him.

**Comment by hmw3** [comment]
done
