### ISSUE TITLE
MAT 15:26 & 27

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/udb-en#82]
There is a question about the use of the word 'little' in these verses. The translator and facilitator do not recall the dogs being referred to as 'little dogs.'

26 Then he told her, "It is not good for someone to take food that has been prepared for his children and throw it to the **_little dogs_** in the house." 27 But the woman replied, "Lord, what you say is correct, but even the **_little dogs_** eat the crumbs that fall to the floor when their masters sit at their own tables and eat!"

**Comment by hmw3** [comment]
4.35 κυνάριον, ου n (diminutive of κύωνa ‘dog,’ 4.34, but in the NT the diminutive force may have become lost, though a component of emotive attachment or affection is no doubt retained and thus the reference is presumably to a house dog)—‘house dog, little dog.’ τὰ κυνάρια ἐσθίει ἀπὸ τῶν ψιχίων τῶν πιπτόντων ἀπὸ τῆς τραπέζης ‘the dogs eat the crumbs falling from the table’ Mt 15:27.

Louw, J. P., & Nida, E. A. (1996). Greek-English lexicon of the New Testament: based on semantic domains (electronic ed. of the 2nd edition., Vol. 1, p. 43). New York: United Bible Societies.

It looks like "doggie," but that wouldn't communicate in some places. I've put in tNs for vv. 26-27 to try to get across the idea that "little" is a term of affection.
