### ISSUE TITLE
HEB 11:8

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/udb-en#90]
The field is asking if the wording "though his did" ..
8God called Abraham to go to the land that he would give his descedants. Because Abraham trusted him, he obeyed God and left his country, even **_though his did_** not know where he was going.

.. should be changed to "though he did".
8God called Abraham to go to the land that he would give his descedants. Because Abraham trusted him, he obeyed God and left his country, even **_though he did_** not know where he was going.

And - shouldn't the word "descedants" be spelled "descendants"?

**Comment by hmw3** [comment]
Now reads

\v 8 God called Abraham to go to the land that he would give his descendants. Because Abraham trusted him, he obeyed God and left his country, even though he did not know where he was going.
