### ISSUE TITLE
Exo 30: 28 UDB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/udb-en#93]
Exo 30:28 UDB: and the altar for offering sacrifices that will be burned, along with its bases and all the things that are used with it.

This lists different things than the ULB and the Bible Hub interlinear glosses. Should the UDB be something like this?

and the altar for offering sacrifices that will be burned and all the things that are used with it, and the basin with its base.

**Comment by hmw3** [comment]
Suggestion taken.

\v 28 and the altar for offering sacrifices that will be burned, along with all the things that are used with it, and the basin and its stand.

**Comment by SusanQuigley** [comment]
Henry, this change isn't showing up yet in the usfm file and on the notes page.

**Comment by hmw3** [comment]
And a good thing, that! I'd left a passive in there. It should work now.

\v 28 and the altar for offering sacrifices that the priests will burn, along with all the things that are used with it, and the basin and its stand.
